/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    AiChatBriefEvent,
    AiChatInput,
    AiChatStreamInput,
    AiChatSubmission,
    ChatStreamProbeEvent,
    ChatStreamProbeInput,
    CodeMessage,
    ValidationError,
} from '../models/index';

export interface CompactConversationRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 是否忽略当前阈值并强制压缩。 / Whether to compact regardless of the current threshold.
     */
    force?: boolean;
}

export interface ContinueChatRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 
     */
    aiChatInput: AiChatInput;
}

export interface CreateChatRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 
     */
    aiChatInput: AiChatInput;
}

export interface InterruptConversationRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
}

export interface ProbeEventStreamRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 
     */
    chatStreamProbeInput: ChatStreamProbeInput;
    /**
     * 可选诊断请求 ID，便于关联客户端与服务端日志。 / Optional diagnostic request ID used to correlate client and server logs.
     */
    xRequestID?: string;
}

export interface StreamChatEventsRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 
     */
    aiChatStreamInput: AiChatStreamInput;
    /**
     * 可选诊断请求 ID，便于关联客户端与服务端日志。 / Optional diagnostic request ID used to correlate client and server logs.
     */
    xRequestID?: string;
}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI {

    /**
     * Creates request options for compactConversation without sending the request
     */
    async compactConversationRequestOpts(requestParameters: CompactConversationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling compactConversation().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling compactConversation().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/compact`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 压缩会话上下文 / Compact conversation context 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 压缩会话上下文 / Compact conversation context
     */
    async compactConversationRaw(requestParameters: CompactConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.compactConversationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 压缩会话上下文 / Compact conversation context 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 压缩会话上下文 / Compact conversation context
     */
    async compactConversation(requestParameters: CompactConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.compactConversationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for continueChat without sending the request
     */
    async continueChatRequestOpts(requestParameters: ContinueChatRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling continueChat().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling continueChat().'
            );
        }

        if (requestParameters['aiChatInput'] == null) {
            throw new runtime.RequiredError(
                'aiChatInput',
                'Required parameter "aiChatInput" was null or undefined when calling continueChat().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['aiChatInput'],
        };
    }

    /**
     * 向已有会话提交消息 / Submit a message to an existing conversation 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 向已有会话提交消息 / Submit a message to an existing conversation
     */
    async continueChatRaw(requestParameters: ContinueChatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiChatSubmission>> {
        const requestOptions = await this.continueChatRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 向已有会话提交消息 / Submit a message to an existing conversation 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 向已有会话提交消息 / Submit a message to an existing conversation
     */
    async continueChat(requestParameters: ContinueChatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiChatSubmission> {
        const response = await this.continueChatRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createChat without sending the request
     */
    async createChatRequestOpts(requestParameters: CreateChatRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling createChat().'
            );
        }

        if (requestParameters['aiChatInput'] == null) {
            throw new runtime.RequiredError(
                'aiChatInput',
                'Required parameter "aiChatInput" was null or undefined when calling createChat().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['aiChatInput'],
        };
    }

    /**
     * 创建会话并提交消息 / Create a conversation and submit a message 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 创建会话并提交消息 / Create a conversation and submit a message
     */
    async createChatRaw(requestParameters: CreateChatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiChatSubmission>> {
        const requestOptions = await this.createChatRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 创建会话并提交消息 / Create a conversation and submit a message 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 创建会话并提交消息 / Create a conversation and submit a message
     */
    async createChat(requestParameters: CreateChatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiChatSubmission> {
        const response = await this.createChatRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for interruptConversation without sending the request
     */
    async interruptConversationRequestOpts(requestParameters: InterruptConversationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling interruptConversation().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling interruptConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/interrupt`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 中断会话执行 / Interrupt conversation execution 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 中断会话执行 / Interrupt conversation execution
     */
    async interruptConversationRaw(requestParameters: InterruptConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.interruptConversationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 中断会话执行 / Interrupt conversation execution 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 中断会话执行 / Interrupt conversation execution
     */
    async interruptConversation(requestParameters: InterruptConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.interruptConversationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for probeEventStream without sending the request
     */
    async probeEventStreamRequestOpts(requestParameters: ProbeEventStreamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling probeEventStream().'
            );
        }

        if (requestParameters['chatStreamProbeInput'] == null) {
            throw new runtime.RequiredError(
                'chatStreamProbeInput',
                'Required parameter "chatStreamProbeInput" was null or undefined when calling probeEventStream().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestID'] != null) {
            headerParameters['X-Request-ID'] = String(requestParameters['xRequestID']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/stream-probe`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['chatStreamProbeInput'],
        };
    }

    /**
     * 探测 SSE 连接 / Probe the SSE connection 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 探测 SSE 连接 / Probe the SSE connection
     */
    async probeEventStreamRaw(requestParameters: ProbeEventStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatStreamProbeEvent>> {
        const requestOptions = await this.probeEventStreamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 探测 SSE 连接 / Probe the SSE connection 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 探测 SSE 连接 / Probe the SSE connection
     */
    async probeEventStream(requestParameters: ProbeEventStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatStreamProbeEvent> {
        const response = await this.probeEventStreamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for streamChatEvents without sending the request
     */
    async streamChatEventsRequestOpts(requestParameters: StreamChatEventsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling streamChatEvents().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling streamChatEvents().'
            );
        }

        if (requestParameters['aiChatStreamInput'] == null) {
            throw new runtime.RequiredError(
                'aiChatStreamInput',
                'Required parameter "aiChatStreamInput" was null or undefined when calling streamChatEvents().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestID'] != null) {
            headerParameters['X-Request-ID'] = String(requestParameters['xRequestID']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/stream`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['aiChatStreamInput'],
        };
    }

    /**
     * 订阅消息事件流 / Stream message events 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 订阅消息事件流 / Stream message events
     */
    async streamChatEventsRaw(requestParameters: StreamChatEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiChatBriefEvent>> {
        const requestOptions = await this.streamChatEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 订阅消息事件流 / Stream message events 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 订阅消息事件流 / Stream message events
     */
    async streamChatEvents(requestParameters: StreamChatEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiChatBriefEvent> {
        const response = await this.streamChatEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
