/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    CodeMessage,
    ConversationActivityBatchInput,
    ConversationActivityList,
    ConversationContextUsage,
    ConversationIds,
    ConversationReadReceipt,
    ConversationReadReceiptInput,
    ConversationShareCreated,
    ConversationShareInput,
    ConversationShareList,
    ConversationShareRevoked,
    ConversationStats,
    ConversationStatusInput,
    ConversationSummaryList,
    ConversationTitle,
    ConversationTitleInput,
    ValidationError,
} from '../models/index';

export interface CreateConversationShareRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 
     */
    conversationShareInput: ConversationShareInput;
}

export interface DeleteConversationRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
}

export interface GetConversationContextUsageRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
}

export interface GetConversationStatsRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
}

export interface GetConversationTitleRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
}

export interface ListActiveConversationsRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
}

export interface ListConversationSharesRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
}

export interface ListConversationsRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 从 0 开始的页码。 / Zero-based page index.
     */
    current?: number;
    /**
     * 单页记录数。 / Number of records per page.
     */
    size?: number;
    /**
     * 排序字段列表。 / Ordered list of sort fields.
     */
    orderBy?: Array<string>;
    /**
     * 排序方向。 / Sort direction.
     */
    orderDirection?: ListConversationsOrderDirectionEnum;
    /**
     * 空值排序策略。 / Null ordering strategy.
     */
    orderNullHandling?: ListConversationsOrderNullHandlingEnum;
    /**
     * 标题或正文检索关键字。 / Title or content search keyword.
     */
    keyword?: string;
    /**
     * 状态过滤条件。 / Status filter.
     */
    status?: string;
}

export interface ListUnreadConversationsRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
}

export interface MarkConversationReadRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 
     */
    conversationReadReceiptInput: ConversationReadReceiptInput;
}

export interface QueryConversationActivitiesRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 
     */
    conversationActivityBatchInput: ConversationActivityBatchInput;
}

export interface RevokeConversationShareRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 会话分享记录 ID。 / Conversation-share record ID.
     */
    shareId: number;
}

export interface UpdateConversationStatusRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 
     */
    conversationStatusInput: ConversationStatusInput;
}

export interface UpdateConversationTitleRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 
     */
    conversationTitleInput: ConversationTitleInput;
}

/**
 * 
 */
export class ConversationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createConversationShare without sending the request
     */
    async createConversationShareRequestOpts(requestParameters: CreateConversationShareRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling createConversationShare().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling createConversationShare().'
            );
        }

        if (requestParameters['conversationShareInput'] == null) {
            throw new runtime.RequiredError(
                'conversationShareInput',
                'Required parameter "conversationShareInput" was null or undefined when calling createConversationShare().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/shares`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['conversationShareInput'],
        };
    }

    /**
     * 创建会话分享 / Create a conversation share 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 创建会话分享 / Create a conversation share
     */
    async createConversationShareRaw(requestParameters: CreateConversationShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationShareCreated>> {
        const requestOptions = await this.createConversationShareRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 创建会话分享 / Create a conversation share 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 创建会话分享 / Create a conversation share
     */
    async createConversationShare(requestParameters: CreateConversationShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationShareCreated> {
        const response = await this.createConversationShareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteConversation without sending the request
     */
    async deleteConversationRequestOpts(requestParameters: DeleteConversationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling deleteConversation().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling deleteConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 删除会话 / Delete a conversation 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 删除会话 / Delete a conversation
     */
    async deleteConversationRaw(requestParameters: DeleteConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteConversationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 删除会话 / Delete a conversation 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 删除会话 / Delete a conversation
     */
    async deleteConversation(requestParameters: DeleteConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConversationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getConversationContextUsage without sending the request
     */
    async getConversationContextUsageRequestOpts(requestParameters: GetConversationContextUsageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getConversationContextUsage().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling getConversationContextUsage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/context-usage`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 读取上下文占用 / Get context usage 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 读取上下文占用 / Get context usage
     */
    async getConversationContextUsageRaw(requestParameters: GetConversationContextUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationContextUsage>> {
        const requestOptions = await this.getConversationContextUsageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 读取上下文占用 / Get context usage 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 读取上下文占用 / Get context usage
     */
    async getConversationContextUsage(requestParameters: GetConversationContextUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationContextUsage> {
        const response = await this.getConversationContextUsageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getConversationStats without sending the request
     */
    async getConversationStatsRequestOpts(requestParameters: GetConversationStatsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getConversationStats().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/stats`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 读取会话统计 / Get conversation statistics 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 读取会话统计 / Get conversation statistics
     */
    async getConversationStatsRaw(requestParameters: GetConversationStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationStats>> {
        const requestOptions = await this.getConversationStatsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 读取会话统计 / Get conversation statistics 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 读取会话统计 / Get conversation statistics
     */
    async getConversationStats(requestParameters: GetConversationStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationStats> {
        const response = await this.getConversationStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getConversationTitle without sending the request
     */
    async getConversationTitleRequestOpts(requestParameters: GetConversationTitleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getConversationTitle().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling getConversationTitle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/title`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 读取会话标题 / Get conversation title 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 读取会话标题 / Get conversation title
     */
    async getConversationTitleRaw(requestParameters: GetConversationTitleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationTitle>> {
        const requestOptions = await this.getConversationTitleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 读取会话标题 / Get conversation title 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 读取会话标题 / Get conversation title
     */
    async getConversationTitle(requestParameters: GetConversationTitleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationTitle> {
        const response = await this.getConversationTitleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listActiveConversations without sending the request
     */
    async listActiveConversationsRequestOpts(requestParameters: ListActiveConversationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling listActiveConversations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/active`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 查询活动会话 / List active conversations 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 查询活动会话 / List active conversations
     */
    async listActiveConversationsRaw(requestParameters: ListActiveConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationIds>> {
        const requestOptions = await this.listActiveConversationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 查询活动会话 / List active conversations 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 查询活动会话 / List active conversations
     */
    async listActiveConversations(requestParameters: ListActiveConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationIds> {
        const response = await this.listActiveConversationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listConversationShares without sending the request
     */
    async listConversationSharesRequestOpts(requestParameters: ListConversationSharesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling listConversationShares().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling listConversationShares().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/shares`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 查询会话分享 / List conversation shares 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 查询会话分享 / List conversation shares
     */
    async listConversationSharesRaw(requestParameters: ListConversationSharesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationShareList>> {
        const requestOptions = await this.listConversationSharesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 查询会话分享 / List conversation shares 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 查询会话分享 / List conversation shares
     */
    async listConversationShares(requestParameters: ListConversationSharesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationShareList> {
        const response = await this.listConversationSharesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listConversations without sending the request
     */
    async listConversationsRequestOpts(requestParameters: ListConversationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling listConversations().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['current'] != null) {
            queryParameters['current'] = requestParameters['current'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['orderBy'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderDirection'] != null) {
            queryParameters['orderDirection'] = requestParameters['orderDirection'];
        }

        if (requestParameters['orderNullHandling'] != null) {
            queryParameters['orderNullHandling'] = requestParameters['orderNullHandling'];
        }

        if (requestParameters['keyword'] != null) {
            queryParameters['keyword'] = requestParameters['keyword'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 分页查询会话 / List conversations 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 分页查询会话 / List conversations
     */
    async listConversationsRaw(requestParameters: ListConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationSummaryList>> {
        const requestOptions = await this.listConversationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 分页查询会话 / List conversations 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 分页查询会话 / List conversations
     */
    async listConversations(requestParameters: ListConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationSummaryList> {
        const response = await this.listConversationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listUnreadConversations without sending the request
     */
    async listUnreadConversationsRequestOpts(requestParameters: ListUnreadConversationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling listUnreadConversations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/unread`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 查询未读会话 / List unread conversations 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 查询未读会话 / List unread conversations
     */
    async listUnreadConversationsRaw(requestParameters: ListUnreadConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationIds>> {
        const requestOptions = await this.listUnreadConversationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 查询未读会话 / List unread conversations 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 查询未读会话 / List unread conversations
     */
    async listUnreadConversations(requestParameters: ListUnreadConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationIds> {
        const response = await this.listUnreadConversationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for markConversationRead without sending the request
     */
    async markConversationReadRequestOpts(requestParameters: MarkConversationReadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling markConversationRead().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling markConversationRead().'
            );
        }

        if (requestParameters['conversationReadReceiptInput'] == null) {
            throw new runtime.RequiredError(
                'conversationReadReceiptInput',
                'Required parameter "conversationReadReceiptInput" was null or undefined when calling markConversationRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/read-receipt`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['conversationReadReceiptInput'],
        };
    }

    /**
     * 推进会话已读游标 / Mark a conversation as read 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 推进会话已读游标 / Mark a conversation as read
     */
    async markConversationReadRaw(requestParameters: MarkConversationReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationReadReceipt>> {
        const requestOptions = await this.markConversationReadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 推进会话已读游标 / Mark a conversation as read 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 推进会话已读游标 / Mark a conversation as read
     */
    async markConversationRead(requestParameters: MarkConversationReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationReadReceipt> {
        const response = await this.markConversationReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for queryConversationActivities without sending the request
     */
    async queryConversationActivitiesRequestOpts(requestParameters: QueryConversationActivitiesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling queryConversationActivities().'
            );
        }

        if (requestParameters['conversationActivityBatchInput'] == null) {
            throw new runtime.RequiredError(
                'conversationActivityBatchInput',
                'Required parameter "conversationActivityBatchInput" was null or undefined when calling queryConversationActivities().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/activity/query`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['conversationActivityBatchInput'],
        };
    }

    /**
     * 批量查询会话活动 / Query conversation activities 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 批量查询会话活动 / Query conversation activities
     */
    async queryConversationActivitiesRaw(requestParameters: QueryConversationActivitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationActivityList>> {
        const requestOptions = await this.queryConversationActivitiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 批量查询会话活动 / Query conversation activities 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 批量查询会话活动 / Query conversation activities
     */
    async queryConversationActivities(requestParameters: QueryConversationActivitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationActivityList> {
        const response = await this.queryConversationActivitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeConversationShare without sending the request
     */
    async revokeConversationShareRequestOpts(requestParameters: RevokeConversationShareRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling revokeConversationShare().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling revokeConversationShare().'
            );
        }

        if (requestParameters['shareId'] == null) {
            throw new runtime.RequiredError(
                'shareId',
                'Required parameter "shareId" was null or undefined when calling revokeConversationShare().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/shares/{shareId}`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));
        urlPath = urlPath.replace('{shareId}', encodeURIComponent(String(requestParameters['shareId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 撤销会话分享 / Revoke a conversation share 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 撤销会话分享 / Revoke a conversation share
     */
    async revokeConversationShareRaw(requestParameters: RevokeConversationShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationShareRevoked>> {
        const requestOptions = await this.revokeConversationShareRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 撤销会话分享 / Revoke a conversation share 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 撤销会话分享 / Revoke a conversation share
     */
    async revokeConversationShare(requestParameters: RevokeConversationShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationShareRevoked> {
        const response = await this.revokeConversationShareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateConversationStatus without sending the request
     */
    async updateConversationStatusRequestOpts(requestParameters: UpdateConversationStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling updateConversationStatus().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling updateConversationStatus().'
            );
        }

        if (requestParameters['conversationStatusInput'] == null) {
            throw new runtime.RequiredError(
                'conversationStatusInput',
                'Required parameter "conversationStatusInput" was null or undefined when calling updateConversationStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/status`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['conversationStatusInput'],
        };
    }

    /**
     * 更新会话状态 / Update conversation status 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 更新会话状态 / Update conversation status
     */
    async updateConversationStatusRaw(requestParameters: UpdateConversationStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateConversationStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 更新会话状态 / Update conversation status 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 更新会话状态 / Update conversation status
     */
    async updateConversationStatus(requestParameters: UpdateConversationStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateConversationStatusRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateConversationTitle without sending the request
     */
    async updateConversationTitleRequestOpts(requestParameters: UpdateConversationTitleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling updateConversationTitle().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling updateConversationTitle().'
            );
        }

        if (requestParameters['conversationTitleInput'] == null) {
            throw new runtime.RequiredError(
                'conversationTitleInput',
                'Required parameter "conversationTitleInput" was null or undefined when calling updateConversationTitle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/title`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['conversationTitleInput'],
        };
    }

    /**
     * 更新会话标题 / Update conversation title 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 更新会话标题 / Update conversation title
     */
    async updateConversationTitleRaw(requestParameters: UpdateConversationTitleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateConversationTitleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 更新会话标题 / Update conversation title 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 更新会话标题 / Update conversation title
     */
    async updateConversationTitle(requestParameters: UpdateConversationTitleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateConversationTitleRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const ListConversationsOrderDirectionEnum = {
    Asc: 'ASC',
    Desc: 'DESC',
} as const;
export type ListConversationsOrderDirectionEnum = typeof ListConversationsOrderDirectionEnum[keyof typeof ListConversationsOrderDirectionEnum];
/**
 * @export
 */
export const ListConversationsOrderNullHandlingEnum = {
    Native: 'NATIVE',
    NullsFirst: 'NULLS_FIRST',
    NullsLast: 'NULLS_LAST',
} as const;
export type ListConversationsOrderNullHandlingEnum = typeof ListConversationsOrderNullHandlingEnum[keyof typeof ListConversationsOrderNullHandlingEnum];
