/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CodeMessage,
    CodeMessageFromJSON,
    CodeMessageToJSON,
} from '../models/CodeMessage';
import {
    type ConversationActivityBatchInput,
    ConversationActivityBatchInputFromJSON,
    ConversationActivityBatchInputToJSON,
} from '../models/ConversationActivityBatchInput';
import {
    type ConversationActivityList,
    ConversationActivityListFromJSON,
    ConversationActivityListToJSON,
} from '../models/ConversationActivityList';
import {
    type ConversationContextUsage,
    ConversationContextUsageFromJSON,
    ConversationContextUsageToJSON,
} from '../models/ConversationContextUsage';
import {
    type ConversationIds,
    ConversationIdsFromJSON,
    ConversationIdsToJSON,
} from '../models/ConversationIds';
import {
    type ConversationReadReceipt,
    ConversationReadReceiptFromJSON,
    ConversationReadReceiptToJSON,
} from '../models/ConversationReadReceipt';
import {
    type ConversationReadReceiptInput,
    ConversationReadReceiptInputFromJSON,
    ConversationReadReceiptInputToJSON,
} from '../models/ConversationReadReceiptInput';
import {
    type ConversationShareCreated,
    ConversationShareCreatedFromJSON,
    ConversationShareCreatedToJSON,
} from '../models/ConversationShareCreated';
import {
    type ConversationShareInput,
    ConversationShareInputFromJSON,
    ConversationShareInputToJSON,
} from '../models/ConversationShareInput';
import {
    type ConversationShareList,
    ConversationShareListFromJSON,
    ConversationShareListToJSON,
} from '../models/ConversationShareList';
import {
    type ConversationShareRevoked,
    ConversationShareRevokedFromJSON,
    ConversationShareRevokedToJSON,
} from '../models/ConversationShareRevoked';
import {
    type ConversationStats,
    ConversationStatsFromJSON,
    ConversationStatsToJSON,
} from '../models/ConversationStats';
import {
    type ConversationStatusInput,
    ConversationStatusInputFromJSON,
    ConversationStatusInputToJSON,
} from '../models/ConversationStatusInput';
import {
    type ConversationSummaryList,
    ConversationSummaryListFromJSON,
    ConversationSummaryListToJSON,
} from '../models/ConversationSummaryList';
import {
    type ConversationTitle,
    ConversationTitleFromJSON,
    ConversationTitleToJSON,
} from '../models/ConversationTitle';
import {
    type ConversationTitleInput,
    ConversationTitleInputFromJSON,
    ConversationTitleInputToJSON,
} from '../models/ConversationTitleInput';
import {
    type ValidationError,
    ValidationErrorFromJSON,
    ValidationErrorToJSON,
} from '../models/ValidationError';

export interface CreateConversationShareRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 
     */
    conversationShareInput: ConversationShareInput;
}

export interface DeleteConversationRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
}

export interface GetConversationContextUsageRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
}

export interface GetConversationStatsRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
}

export interface GetConversationTitleRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
}

export interface ListActiveConversationsRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
}

export interface ListConversationSharesRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
}

export interface ListConversationsRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 从 0 开始的页码。 / Zero-based page index.
     */
    current?: number;
    /**
     * 单页记录数。 / Number of records per page.
     */
    size?: number;
    /**
     * 排序字段列表。 / Ordered list of sort fields.
     */
    orderBy?: Array<string>;
    /**
     * 排序方向。 / Sort direction.
     */
    orderDirection?: ListConversationsOrderDirectionEnum;
    /**
     * 空值排序策略。 / Null ordering strategy.
     */
    orderNullHandling?: ListConversationsOrderNullHandlingEnum;
    /**
     * 标题或正文检索关键字。 / Title or content search keyword.
     */
    keyword?: string;
    /**
     * 状态过滤条件。 / Status filter.
     */
    status?: string;
}

export interface ListUnreadConversationsRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
}

export interface MarkConversationReadRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 
     */
    conversationReadReceiptInput: ConversationReadReceiptInput;
}

export interface QueryConversationActivitiesRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 
     */
    conversationActivityBatchInput: ConversationActivityBatchInput;
}

export interface RevokeConversationShareRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 会话分享记录 ID。 / Conversation-share record ID.
     */
    shareId: number;
}

export interface UpdateConversationStatusRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 
     */
    conversationStatusInput: ConversationStatusInput;
}

export interface UpdateConversationTitleRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 
     */
    conversationTitleInput: ConversationTitleInput;
}

/**
 * 
 */
export class ConversationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createConversationShare without sending the request
     */
    async createConversationShareRequestOpts(requestParameters: CreateConversationShareRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling createConversationShare().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling createConversationShare().'
            );
        }

        if (requestParameters['conversationShareInput'] == null) {
            throw new runtime.RequiredError(
                'conversationShareInput',
                'Required parameter "conversationShareInput" was null or undefined when calling createConversationShare().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/shares`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConversationShareInputToJSON(requestParameters['conversationShareInput']),
        };
    }

    /**
     * ### 使用场景 为会话创建受控的外部分享。  ### Use case Create controlled external sharing for a conversation.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 创建新的分享记录和分享码。  ### Behavior and side effects Creates a share record and share code.  ### 后续调用 安全地交付分享信息，并定期检查有效期。  ### Next step Deliver share information securely and monitor its expiry.  ### 接口摘要 创建会话分享 / Create a conversation share  ### Operation summary 创建会话分享 / Create a conversation share
     * 创建会话分享 / Create a conversation share
     */
    async createConversationShareRaw(requestParameters: CreateConversationShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationShareCreated>> {
        const requestOptions = await this.createConversationShareRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationShareCreatedFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 为会话创建受控的外部分享。  ### Use case Create controlled external sharing for a conversation.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 创建新的分享记录和分享码。  ### Behavior and side effects Creates a share record and share code.  ### 后续调用 安全地交付分享信息，并定期检查有效期。  ### Next step Deliver share information securely and monitor its expiry.  ### 接口摘要 创建会话分享 / Create a conversation share  ### Operation summary 创建会话分享 / Create a conversation share
     * 创建会话分享 / Create a conversation share
     */
    async createConversationShare(requestParameters: CreateConversationShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationShareCreated> {
        const response = await this.createConversationShareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteConversation without sending the request
     */
    async deleteConversationRequestOpts(requestParameters: DeleteConversationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling deleteConversation().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling deleteConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ### 使用场景 永久移除用户不再需要的会话。  ### Use case Permanently remove a conversation the user no longer needs.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 删除会话及其可见关联数据。  ### Behavior and side effects Deletes the conversation and its visible related data.  ### 后续调用 从本地列表和缓存中移除该会话。  ### Next step Remove the conversation from local lists and caches.  ### 接口摘要 删除会话 / Delete a conversation  ### Operation summary 删除会话 / Delete a conversation
     * 删除会话 / Delete a conversation
     */
    async deleteConversationRaw(requestParameters: DeleteConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteConversationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ### 使用场景 永久移除用户不再需要的会话。  ### Use case Permanently remove a conversation the user no longer needs.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 删除会话及其可见关联数据。  ### Behavior and side effects Deletes the conversation and its visible related data.  ### 后续调用 从本地列表和缓存中移除该会话。  ### Next step Remove the conversation from local lists and caches.  ### 接口摘要 删除会话 / Delete a conversation  ### Operation summary 删除会话 / Delete a conversation
     * 删除会话 / Delete a conversation
     */
    async deleteConversation(requestParameters: DeleteConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConversationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getConversationContextUsage without sending the request
     */
    async getConversationContextUsageRequestOpts(requestParameters: GetConversationContextUsageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getConversationContextUsage().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling getConversationContextUsage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/context-usage`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ### 使用场景 决定是否需要压缩上下文或提示容量时读取占用。  ### Use case Read context usage to decide whether to compact or warn about capacity.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 只读。  ### Behavior and side effects Read-only.  ### 后续调用 达到阈值时调用 compactConversation。  ### Next step Call compactConversation when the threshold is reached.  ### 接口摘要 读取上下文占用 / Get context usage  ### Operation summary 读取上下文占用 / Get context usage
     * 读取上下文占用 / Get context usage
     */
    async getConversationContextUsageRaw(requestParameters: GetConversationContextUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationContextUsage>> {
        const requestOptions = await this.getConversationContextUsageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationContextUsageFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 决定是否需要压缩上下文或提示容量时读取占用。  ### Use case Read context usage to decide whether to compact or warn about capacity.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 只读。  ### Behavior and side effects Read-only.  ### 后续调用 达到阈值时调用 compactConversation。  ### Next step Call compactConversation when the threshold is reached.  ### 接口摘要 读取上下文占用 / Get context usage  ### Operation summary 读取上下文占用 / Get context usage
     * 读取上下文占用 / Get context usage
     */
    async getConversationContextUsage(requestParameters: GetConversationContextUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationContextUsage> {
        const response = await this.getConversationContextUsageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getConversationStats without sending the request
     */
    async getConversationStatsRequestOpts(requestParameters: GetConversationStatsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getConversationStats().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/stats`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ### 使用场景 展示当前用户在渠道中的会话聚合统计。  ### Use case Display aggregate conversation statistics for the current user in the channel.  ### 前置条件 外部用户已配置。  ### Prerequisites The external user is configured.  ### 行为与副作用 只读。  ### Behavior and side effects Read-only.  ### 后续调用 用于仪表盘展示，不作为逐会话状态来源。  ### Next step Use for dashboards, not as per-conversation state.  ### 接口摘要 读取会话统计 / Get conversation statistics  ### Operation summary 读取会话统计 / Get conversation statistics
     * 读取会话统计 / Get conversation statistics
     */
    async getConversationStatsRaw(requestParameters: GetConversationStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationStats>> {
        const requestOptions = await this.getConversationStatsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationStatsFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 展示当前用户在渠道中的会话聚合统计。  ### Use case Display aggregate conversation statistics for the current user in the channel.  ### 前置条件 外部用户已配置。  ### Prerequisites The external user is configured.  ### 行为与副作用 只读。  ### Behavior and side effects Read-only.  ### 后续调用 用于仪表盘展示，不作为逐会话状态来源。  ### Next step Use for dashboards, not as per-conversation state.  ### 接口摘要 读取会话统计 / Get conversation statistics  ### Operation summary 读取会话统计 / Get conversation statistics
     * 读取会话统计 / Get conversation statistics
     */
    async getConversationStats(requestParameters: GetConversationStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationStats> {
        const response = await this.getConversationStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getConversationTitle without sending the request
     */
    async getConversationTitleRequestOpts(requestParameters: GetConversationTitleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getConversationTitle().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling getConversationTitle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/title`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ### 使用场景 读取自动生成或用户设置的会话标题。  ### Use case Read the generated or user-defined conversation title.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 只读。  ### Behavior and side effects Read-only.  ### 后续调用 生成中时稍后重试，或允许用户更新标题。  ### Next step Retry while generation is pending or let the user update the title.  ### 接口摘要 读取会话标题 / Get conversation title  ### Operation summary 读取会话标题 / Get conversation title
     * 读取会话标题 / Get conversation title
     */
    async getConversationTitleRaw(requestParameters: GetConversationTitleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationTitle>> {
        const requestOptions = await this.getConversationTitleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationTitleFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 读取自动生成或用户设置的会话标题。  ### Use case Read the generated or user-defined conversation title.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 只读。  ### Behavior and side effects Read-only.  ### 后续调用 生成中时稍后重试，或允许用户更新标题。  ### Next step Retry while generation is pending or let the user update the title.  ### 接口摘要 读取会话标题 / Get conversation title  ### Operation summary 读取会话标题 / Get conversation title
     * 读取会话标题 / Get conversation title
     */
    async getConversationTitle(requestParameters: GetConversationTitleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationTitle> {
        const response = await this.getConversationTitleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listActiveConversations without sending the request
     */
    async listActiveConversationsRequestOpts(requestParameters: ListActiveConversationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling listActiveConversations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/active`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ### 使用场景 快速恢复当前仍在执行的会话。  ### Use case Quickly recover conversations that are still executing.  ### 前置条件 外部用户已配置。  ### Prerequisites The external user is configured.  ### 行为与副作用 只读，返回会话 ID。  ### Behavior and side effects Read-only and returns conversation IDs.  ### 后续调用 批量查询活动详情或重新连接 SSE。  ### Next step Batch-query activity details or reconnect SSE.  ### 接口摘要 查询活动会话 / List active conversations  ### Operation summary 查询活动会话 / List active conversations
     * 查询活动会话 / List active conversations
     */
    async listActiveConversationsRaw(requestParameters: ListActiveConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationIds>> {
        const requestOptions = await this.listActiveConversationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationIdsFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 快速恢复当前仍在执行的会话。  ### Use case Quickly recover conversations that are still executing.  ### 前置条件 外部用户已配置。  ### Prerequisites The external user is configured.  ### 行为与副作用 只读，返回会话 ID。  ### Behavior and side effects Read-only and returns conversation IDs.  ### 后续调用 批量查询活动详情或重新连接 SSE。  ### Next step Batch-query activity details or reconnect SSE.  ### 接口摘要 查询活动会话 / List active conversations  ### Operation summary 查询活动会话 / List active conversations
     * 查询活动会话 / List active conversations
     */
    async listActiveConversations(requestParameters: ListActiveConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationIds> {
        const response = await this.listActiveConversationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listConversationShares without sending the request
     */
    async listConversationSharesRequestOpts(requestParameters: ListConversationSharesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling listConversationShares().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling listConversationShares().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/shares`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ### 使用场景 查看会话当前创建的分享记录。  ### Use case Inspect the conversation\'s current share records.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 只读。  ### Behavior and side effects Read-only.  ### 后续调用 按需创建新分享或撤销旧分享。  ### Next step Create a new share or revoke an existing one as needed.  ### 接口摘要 查询会话分享 / List conversation shares  ### Operation summary 查询会话分享 / List conversation shares
     * 查询会话分享 / List conversation shares
     */
    async listConversationSharesRaw(requestParameters: ListConversationSharesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationShareList>> {
        const requestOptions = await this.listConversationSharesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationShareListFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 查看会话当前创建的分享记录。  ### Use case Inspect the conversation\'s current share records.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 只读。  ### Behavior and side effects Read-only.  ### 后续调用 按需创建新分享或撤销旧分享。  ### Next step Create a new share or revoke an existing one as needed.  ### 接口摘要 查询会话分享 / List conversation shares  ### Operation summary 查询会话分享 / List conversation shares
     * 查询会话分享 / List conversation shares
     */
    async listConversationShares(requestParameters: ListConversationSharesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationShareList> {
        const response = await this.listConversationSharesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listConversations without sending the request
     */
    async listConversationsRequestOpts(requestParameters: ListConversationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling listConversations().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['current'] != null) {
            queryParameters['current'] = requestParameters['current'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['orderBy'] = requestParameters['orderBy'];
        }

        if (requestParameters['orderDirection'] != null) {
            queryParameters['orderDirection'] = requestParameters['orderDirection'];
        }

        if (requestParameters['orderNullHandling'] != null) {
            queryParameters['orderNullHandling'] = requestParameters['orderNullHandling'];
        }

        if (requestParameters['keyword'] != null) {
            queryParameters['keyword'] = requestParameters['keyword'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ### 使用场景 构建用户的分页会话列表与搜索结果。  ### Use case Build the user\'s paged conversation list and search results.  ### 前置条件 外部用户已配置。  ### Prerequisites The external user is configured.  ### 行为与副作用 只读，返回分页记录。  ### Behavior and side effects Read-only and returns paged records.  ### 后续调用 按需读取标题、活动状态或消息。  ### Next step Read titles, activity, or messages as needed.  ### 接口摘要 分页查询会话 / List conversations  ### Operation summary 分页查询会话 / List conversations
     * 分页查询会话 / List conversations
     */
    async listConversationsRaw(requestParameters: ListConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationSummaryList>> {
        const requestOptions = await this.listConversationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationSummaryListFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 构建用户的分页会话列表与搜索结果。  ### Use case Build the user\'s paged conversation list and search results.  ### 前置条件 外部用户已配置。  ### Prerequisites The external user is configured.  ### 行为与副作用 只读，返回分页记录。  ### Behavior and side effects Read-only and returns paged records.  ### 后续调用 按需读取标题、活动状态或消息。  ### Next step Read titles, activity, or messages as needed.  ### 接口摘要 分页查询会话 / List conversations  ### Operation summary 分页查询会话 / List conversations
     * 分页查询会话 / List conversations
     */
    async listConversations(requestParameters: ListConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationSummaryList> {
        const response = await this.listConversationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listUnreadConversations without sending the request
     */
    async listUnreadConversationsRequestOpts(requestParameters: ListUnreadConversationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling listUnreadConversations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/unread`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ### 使用场景 显示存在未读完成结果的会话角标。  ### Use case Display conversations with unread completed results.  ### 前置条件 外部用户已配置。  ### Prerequisites The external user is configured.  ### 行为与副作用 只读，返回未读会话 ID。  ### Behavior and side effects Read-only and returns unread conversation IDs.  ### 后续调用 读取消息后推进已读游标。  ### Next step Advance the read cursor after reading messages.  ### 接口摘要 查询未读会话 / List unread conversations  ### Operation summary 查询未读会话 / List unread conversations
     * 查询未读会话 / List unread conversations
     */
    async listUnreadConversationsRaw(requestParameters: ListUnreadConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationIds>> {
        const requestOptions = await this.listUnreadConversationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationIdsFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 显示存在未读完成结果的会话角标。  ### Use case Display conversations with unread completed results.  ### 前置条件 外部用户已配置。  ### Prerequisites The external user is configured.  ### 行为与副作用 只读，返回未读会话 ID。  ### Behavior and side effects Read-only and returns unread conversation IDs.  ### 后续调用 读取消息后推进已读游标。  ### Next step Advance the read cursor after reading messages.  ### 接口摘要 查询未读会话 / List unread conversations  ### Operation summary 查询未读会话 / List unread conversations
     * 查询未读会话 / List unread conversations
     */
    async listUnreadConversations(requestParameters: ListUnreadConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationIds> {
        const response = await this.listUnreadConversationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for markConversationRead without sending the request
     */
    async markConversationReadRequestOpts(requestParameters: MarkConversationReadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling markConversationRead().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling markConversationRead().'
            );
        }

        if (requestParameters['conversationReadReceiptInput'] == null) {
            throw new runtime.RequiredError(
                'conversationReadReceiptInput',
                'Required parameter "conversationReadReceiptInput" was null or undefined when calling markConversationRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/read-receipt`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ConversationReadReceiptInputToJSON(requestParameters['conversationReadReceiptInput']),
        };
    }

    /**
     * ### 使用场景 用户查看结果后推进会话已读位置。  ### Use case Advance a conversation\'s read position after the user views a result.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 更新已读游标，不删除消息。  ### Behavior and side effects Updates the read cursor without deleting messages.  ### 后续调用 刷新未读会话列表。  ### Next step Refresh the unread conversation list.  ### 接口摘要 推进会话已读游标 / Mark a conversation as read  ### Operation summary 推进会话已读游标 / Mark a conversation as read
     * 推进会话已读游标 / Mark a conversation as read
     */
    async markConversationReadRaw(requestParameters: MarkConversationReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationReadReceipt>> {
        const requestOptions = await this.markConversationReadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationReadReceiptFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 用户查看结果后推进会话已读位置。  ### Use case Advance a conversation\'s read position after the user views a result.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 更新已读游标，不删除消息。  ### Behavior and side effects Updates the read cursor without deleting messages.  ### 后续调用 刷新未读会话列表。  ### Next step Refresh the unread conversation list.  ### 接口摘要 推进会话已读游标 / Mark a conversation as read  ### Operation summary 推进会话已读游标 / Mark a conversation as read
     * 推进会话已读游标 / Mark a conversation as read
     */
    async markConversationRead(requestParameters: MarkConversationReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationReadReceipt> {
        const response = await this.markConversationReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for queryConversationActivities without sending the request
     */
    async queryConversationActivitiesRequestOpts(requestParameters: QueryConversationActivitiesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling queryConversationActivities().'
            );
        }

        if (requestParameters['conversationActivityBatchInput'] == null) {
            throw new runtime.RequiredError(
                'conversationActivityBatchInput',
                'Required parameter "conversationActivityBatchInput" was null or undefined when calling queryConversationActivities().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/activity/query`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConversationActivityBatchInputToJSON(requestParameters['conversationActivityBatchInput']),
        };
    }

    /**
     * ### 使用场景 批量刷新多个会话的执行与未读状态。  ### Use case Refresh execution and unread state for multiple conversations in one request.  ### 前置条件 已持有最多 1000 个当前用户的会话 ID。  ### Prerequisites Up to 1000 conversation IDs for the current user are available.  ### 行为与副作用 只读，返回每个会话的活动投影。  ### Behavior and side effects Read-only and returns an activity projection per conversation.  ### 后续调用 更新列表状态并恢复必要的流。  ### Next step Update list state and recover any required streams.  ### 接口摘要 批量查询会话活动 / Query conversation activities  ### Operation summary 批量查询会话活动 / Query conversation activities
     * 批量查询会话活动 / Query conversation activities
     */
    async queryConversationActivitiesRaw(requestParameters: QueryConversationActivitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationActivityList>> {
        const requestOptions = await this.queryConversationActivitiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationActivityListFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 批量刷新多个会话的执行与未读状态。  ### Use case Refresh execution and unread state for multiple conversations in one request.  ### 前置条件 已持有最多 1000 个当前用户的会话 ID。  ### Prerequisites Up to 1000 conversation IDs for the current user are available.  ### 行为与副作用 只读，返回每个会话的活动投影。  ### Behavior and side effects Read-only and returns an activity projection per conversation.  ### 后续调用 更新列表状态并恢复必要的流。  ### Next step Update list state and recover any required streams.  ### 接口摘要 批量查询会话活动 / Query conversation activities  ### Operation summary 批量查询会话活动 / Query conversation activities
     * 批量查询会话活动 / Query conversation activities
     */
    async queryConversationActivities(requestParameters: QueryConversationActivitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationActivityList> {
        const response = await this.queryConversationActivitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeConversationShare without sending the request
     */
    async revokeConversationShareRequestOpts(requestParameters: RevokeConversationShareRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling revokeConversationShare().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling revokeConversationShare().'
            );
        }

        if (requestParameters['shareId'] == null) {
            throw new runtime.RequiredError(
                'shareId',
                'Required parameter "shareId" was null or undefined when calling revokeConversationShare().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/shares/{shareId}`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));
        urlPath = urlPath.replace('{shareId}', encodeURIComponent(String(requestParameters['shareId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ### 使用场景 使不再需要的分享立即失效。  ### Use case Invalidate a share that is no longer needed.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 撤销指定分享，不删除原会话。  ### Behavior and side effects Revokes the selected share without deleting the conversation.  ### 后续调用 刷新分享列表并停止分发旧链接。  ### Next step Refresh the share list and stop distributing the old link.  ### 接口摘要 撤销会话分享 / Revoke a conversation share  ### Operation summary 撤销会话分享 / Revoke a conversation share
     * 撤销会话分享 / Revoke a conversation share
     */
    async revokeConversationShareRaw(requestParameters: RevokeConversationShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationShareRevoked>> {
        const requestOptions = await this.revokeConversationShareRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationShareRevokedFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 使不再需要的分享立即失效。  ### Use case Invalidate a share that is no longer needed.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 撤销指定分享，不删除原会话。  ### Behavior and side effects Revokes the selected share without deleting the conversation.  ### 后续调用 刷新分享列表并停止分发旧链接。  ### Next step Refresh the share list and stop distributing the old link.  ### 接口摘要 撤销会话分享 / Revoke a conversation share  ### Operation summary 撤销会话分享 / Revoke a conversation share
     * 撤销会话分享 / Revoke a conversation share
     */
    async revokeConversationShare(requestParameters: RevokeConversationShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationShareRevoked> {
        const response = await this.revokeConversationShareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateConversationStatus without sending the request
     */
    async updateConversationStatusRequestOpts(requestParameters: UpdateConversationStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling updateConversationStatus().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling updateConversationStatus().'
            );
        }

        if (requestParameters['conversationStatusInput'] == null) {
            throw new runtime.RequiredError(
                'conversationStatusInput',
                'Required parameter "conversationStatusInput" was null or undefined when calling updateConversationStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/status`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ConversationStatusInputToJSON(requestParameters['conversationStatusInput']),
        };
    }

    /**
     * ### 使用场景 归档、恢复或切换会话业务状态。  ### Use case Archive, restore, or otherwise change conversation business status.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 异步更新会话状态。  ### Behavior and side effects Updates conversation status asynchronously.  ### 后续调用 按新状态刷新会话列表。  ### Next step Refresh conversation lists using the new status.  ### 接口摘要 更新会话状态 / Update conversation status  ### Operation summary 更新会话状态 / Update conversation status
     * 更新会话状态 / Update conversation status
     */
    async updateConversationStatusRaw(requestParameters: UpdateConversationStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateConversationStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ### 使用场景 归档、恢复或切换会话业务状态。  ### Use case Archive, restore, or otherwise change conversation business status.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 异步更新会话状态。  ### Behavior and side effects Updates conversation status asynchronously.  ### 后续调用 按新状态刷新会话列表。  ### Next step Refresh conversation lists using the new status.  ### 接口摘要 更新会话状态 / Update conversation status  ### Operation summary 更新会话状态 / Update conversation status
     * 更新会话状态 / Update conversation status
     */
    async updateConversationStatus(requestParameters: UpdateConversationStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateConversationStatusRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateConversationTitle without sending the request
     */
    async updateConversationTitleRequestOpts(requestParameters: UpdateConversationTitleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling updateConversationTitle().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling updateConversationTitle().'
            );
        }

        if (requestParameters['conversationTitleInput'] == null) {
            throw new runtime.RequiredError(
                'conversationTitleInput',
                'Required parameter "conversationTitleInput" was null or undefined when calling updateConversationTitle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/title`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ConversationTitleInputToJSON(requestParameters['conversationTitleInput']),
        };
    }

    /**
     * ### 使用场景 保存用户编辑的会话标题。  ### Use case Save a user-edited conversation title.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 异步更新标题。  ### Behavior and side effects Updates the title asynchronously.  ### 后续调用 重新读取标题或刷新列表。  ### Next step Read the title again or refresh the list.  ### 接口摘要 更新会话标题 / Update conversation title  ### Operation summary 更新会话标题 / Update conversation title
     * 更新会话标题 / Update conversation title
     */
    async updateConversationTitleRaw(requestParameters: UpdateConversationTitleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateConversationTitleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ### 使用场景 保存用户编辑的会话标题。  ### Use case Save a user-edited conversation title.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 异步更新标题。  ### Behavior and side effects Updates the title asynchronously.  ### 后续调用 重新读取标题或刷新列表。  ### Next step Read the title again or refresh the list.  ### 接口摘要 更新会话标题 / Update conversation title  ### Operation summary 更新会话标题 / Update conversation title
     * 更新会话标题 / Update conversation title
     */
    async updateConversationTitle(requestParameters: UpdateConversationTitleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateConversationTitleRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const ListConversationsOrderDirectionEnum = {
    Asc: 'ASC',
    Desc: 'DESC',
} as const;
export type ListConversationsOrderDirectionEnum = typeof ListConversationsOrderDirectionEnum[keyof typeof ListConversationsOrderDirectionEnum];
/**
 * @export
 */
export const ListConversationsOrderNullHandlingEnum = {
    Native: 'NATIVE',
    NullsFirst: 'NULLS_FIRST',
    NullsLast: 'NULLS_LAST',
} as const;
export type ListConversationsOrderNullHandlingEnum = typeof ListConversationsOrderNullHandlingEnum[keyof typeof ListConversationsOrderNullHandlingEnum];
