/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    AiChatBriefEventList,
    AiChatEventsBatch,
    AiChatEventsBatchInput,
    CodeMessage,
    ValidationError,
} from '../models/index';

export interface GetChatEventsRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 用户消息 ID；必须属于指定会话。 / User-message ID owned by the specified conversation.
     */
    messageId: string;
}

export interface GetChatEventsBatchRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 
     */
    aiChatEventsBatchInput: AiChatEventsBatchInput;
}

/**
 * 
 */
export class EventsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getChatEvents without sending the request
     */
    async getChatEventsRequestOpts(requestParameters: GetChatEventsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getChatEvents().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling getChatEvents().'
            );
        }

        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling getChatEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['conversationId'] != null) {
            queryParameters['conversationId'] = requestParameters['conversationId'];
        }

        if (requestParameters['messageId'] != null) {
            queryParameters['messageId'] = requestParameters['messageId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/events`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 读取消息事件 / Get message events 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 读取消息事件 / Get message events
     */
    async getChatEventsRaw(requestParameters: GetChatEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiChatBriefEventList>> {
        const requestOptions = await this.getChatEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 读取消息事件 / Get message events 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 读取消息事件 / Get message events
     */
    async getChatEvents(requestParameters: GetChatEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiChatBriefEventList> {
        const response = await this.getChatEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getChatEventsBatch without sending the request
     */
    async getChatEventsBatchRequestOpts(requestParameters: GetChatEventsBatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getChatEventsBatch().'
            );
        }

        if (requestParameters['aiChatEventsBatchInput'] == null) {
            throw new runtime.RequiredError(
                'aiChatEventsBatchInput',
                'Required parameter "aiChatEventsBatchInput" was null or undefined when calling getChatEventsBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/events/batch`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['aiChatEventsBatchInput'],
        };
    }

    /**
     * 批量读取消息事件 / Get message events in batch 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 批量读取消息事件 / Get message events in batch
     */
    async getChatEventsBatchRaw(requestParameters: GetChatEventsBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiChatEventsBatch>> {
        const requestOptions = await this.getChatEventsBatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 批量读取消息事件 / Get message events in batch 请求会在身份验签和资源归属校验后执行；响应字段以本契约为准。 / The request runs after signature and resource-ownership validation; this contract defines the response fields.
     * 批量读取消息事件 / Get message events in batch
     */
    async getChatEventsBatch(requestParameters: GetChatEventsBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiChatEventsBatch> {
        const response = await this.getChatEventsBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
