/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AgentFile,
    AgentFileFromJSON,
    AgentFileToJSON,
} from '../models/AgentFile';
import {
    type CodeMessage,
    CodeMessageFromJSON,
    CodeMessageToJSON,
} from '../models/CodeMessage';
import {
    type ConfirmUploadInput,
    ConfirmUploadInputFromJSON,
    ConfirmUploadInputToJSON,
} from '../models/ConfirmUploadInput';
import {
    type CreateFileInput,
    CreateFileInputFromJSON,
    CreateFileInputToJSON,
} from '../models/CreateFileInput';
import {
    type FileExists,
    FileExistsFromJSON,
    FileExistsToJSON,
} from '../models/FileExists';
import {
    type GeneratePreSignedUrlInput,
    GeneratePreSignedUrlInputFromJSON,
    GeneratePreSignedUrlInputToJSON,
} from '../models/GeneratePreSignedUrlInput';
import {
    type GeneratePreSignedUrlOutput,
    GeneratePreSignedUrlOutputFromJSON,
    GeneratePreSignedUrlOutputToJSON,
} from '../models/GeneratePreSignedUrlOutput';
import {
    type PreSignedReadUrl,
    PreSignedReadUrlFromJSON,
    PreSignedReadUrlToJSON,
} from '../models/PreSignedReadUrl';
import {
    type ValidationError,
    ValidationErrorFromJSON,
    ValidationErrorToJSON,
} from '../models/ValidationError';

export interface ConfirmPreSignedUploadRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 
     */
    confirmUploadInput: ConfirmUploadInput;
}

export interface CreateFileByContentMd5Request {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 
     */
    createFileInput: CreateFileInput;
}

export interface CreatePreSignedUploadRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 
     */
    generatePreSignedUrlInput: GeneratePreSignedUrlInput;
}

export interface FileExistsByContentMd5Request {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 文件内容 MD5。 / MD5 digest of the file content.
     */
    contentMd5: string;
}

export interface GetConversationFilePreviewRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 文件记录 ID。 / File record ID.
     */
    fileId: number;
}

export interface GetPlanIntermediateFilePreviewRequest {
    /**
     * Agent OpenAPI 渠道 UUID。 / Agent OpenAPI channel UUID.
     */
    channelId: string;
    /**
     * 会话 ID；必须属于当前外部用户。 / Conversation ID owned by the current external user.
     */
    conversationId: string;
    /**
     * 用户消息 ID；必须属于指定会话。 / User-message ID owned by the specified conversation.
     */
    messageId: string;
    /**
     * 文件记录 ID。 / File record ID.
     */
    fileId: number;
}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI {

    /**
     * Creates request options for confirmPreSignedUpload without sending the request
     */
    async confirmPreSignedUploadRequestOpts(requestParameters: ConfirmPreSignedUploadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling confirmPreSignedUpload().'
            );
        }

        if (requestParameters['confirmUploadInput'] == null) {
            throw new runtime.RequiredError(
                'confirmUploadInput',
                'Required parameter "confirmUploadInput" was null or undefined when calling confirmPreSignedUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/files/pre-signed-url/confirm`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmUploadInputToJSON(requestParameters['confirmUploadInput']),
        };
    }

    /**
     * ### 使用场景 对象存储上传成功后登记文件。  ### Use case Register a file after object-storage upload succeeds.  ### 前置条件 持有预签名响应的 fileUk 和同一 contentMd5。  ### Prerequisites The fileUk and matching contentMd5 from the presign response are available.  ### 行为与副作用 确认文件并返回可用于聊天的文件记录。  ### Behavior and side effects Confirms the file and returns a record usable in chat.  ### 后续调用 把返回的文件 ID 放入聊天请求。  ### Next step Place the returned file ID in a chat request.  ### 接口摘要 确认预签名上传 / Confirm a presigned upload  ### Operation summary 确认预签名上传 / Confirm a presigned upload
     * 确认预签名上传 / Confirm a presigned upload
     */
    async confirmPreSignedUploadRaw(requestParameters: ConfirmPreSignedUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentFile>> {
        const requestOptions = await this.confirmPreSignedUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentFileFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 对象存储上传成功后登记文件。  ### Use case Register a file after object-storage upload succeeds.  ### 前置条件 持有预签名响应的 fileUk 和同一 contentMd5。  ### Prerequisites The fileUk and matching contentMd5 from the presign response are available.  ### 行为与副作用 确认文件并返回可用于聊天的文件记录。  ### Behavior and side effects Confirms the file and returns a record usable in chat.  ### 后续调用 把返回的文件 ID 放入聊天请求。  ### Next step Place the returned file ID in a chat request.  ### 接口摘要 确认预签名上传 / Confirm a presigned upload  ### Operation summary 确认预签名上传 / Confirm a presigned upload
     * 确认预签名上传 / Confirm a presigned upload
     */
    async confirmPreSignedUpload(requestParameters: ConfirmPreSignedUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentFile> {
        const response = await this.confirmPreSignedUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createFileByContentMd5 without sending the request
     */
    async createFileByContentMd5RequestOpts(requestParameters: CreateFileByContentMd5Request): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling createFileByContentMd5().'
            );
        }

        if (requestParameters['createFileInput'] == null) {
            throw new runtime.RequiredError(
                'createFileInput',
                'Required parameter "createFileInput" was null or undefined when calling createFileByContentMd5().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/files/contentMd5`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateFileInputToJSON(requestParameters['createFileInput']),
        };
    }

    /**
     * ### 使用场景 复用服务端已经存在的相同内容文件。  ### Use case Reuse an existing server-side file with identical content.  ### 前置条件 已计算 MD5 并确认内容可复用。  ### Prerequisites The MD5 is known and the content is safe to reuse.  ### 行为与副作用 创建当前用户可引用的文件记录，不上传字节。  ### Behavior and side effects Creates a user-visible file record without uploading bytes.  ### 后续调用 把返回的文件 ID 放入聊天请求。  ### Next step Place the returned file ID in a chat request.  ### 接口摘要 按 MD5 复用文件 / Reuse a file by MD5  ### Operation summary 按 MD5 复用文件 / Reuse a file by MD5
     * 按 MD5 复用文件 / Reuse a file by MD5
     */
    async createFileByContentMd5Raw(requestParameters: CreateFileByContentMd5Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentFile>> {
        const requestOptions = await this.createFileByContentMd5RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentFileFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 复用服务端已经存在的相同内容文件。  ### Use case Reuse an existing server-side file with identical content.  ### 前置条件 已计算 MD5 并确认内容可复用。  ### Prerequisites The MD5 is known and the content is safe to reuse.  ### 行为与副作用 创建当前用户可引用的文件记录，不上传字节。  ### Behavior and side effects Creates a user-visible file record without uploading bytes.  ### 后续调用 把返回的文件 ID 放入聊天请求。  ### Next step Place the returned file ID in a chat request.  ### 接口摘要 按 MD5 复用文件 / Reuse a file by MD5  ### Operation summary 按 MD5 复用文件 / Reuse a file by MD5
     * 按 MD5 复用文件 / Reuse a file by MD5
     */
    async createFileByContentMd5(requestParameters: CreateFileByContentMd5Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentFile> {
        const response = await this.createFileByContentMd5Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createPreSignedUpload without sending the request
     */
    async createPreSignedUploadRequestOpts(requestParameters: CreatePreSignedUploadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling createPreSignedUpload().'
            );
        }

        if (requestParameters['generatePreSignedUrlInput'] == null) {
            throw new runtime.RequiredError(
                'generatePreSignedUrlInput',
                'Required parameter "generatePreSignedUrlInput" was null or undefined when calling createPreSignedUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/files/pre-signed-url/write`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GeneratePreSignedUrlInputToJSON(requestParameters['generatePreSignedUrlInput']),
        };
    }

    /**
     * ### 使用场景 为需要上传的新附件申请对象存储地址。  ### Use case Request an object-storage URL for a new attachment.  ### 前置条件 已计算文件 MD5，文件模块为 ai-chat-attachments。  ### Prerequisites The file MD5 is known and the module is ai-chat-attachments.  ### 行为与副作用 创建短期上传授权，不代表上传完成。  ### Behavior and side effects Creates short-lived upload authorization; upload is not yet complete.  ### 后续调用 按返回 headers 上传文件，再调用确认接口。  ### Next step Upload with the returned headers, then call confirmation.  ### 接口摘要 创建预签名上传地址 / Create a presigned upload URL  ### Operation summary 创建预签名上传地址 / Create a presigned upload URL
     * 创建预签名上传地址 / Create a presigned upload URL
     */
    async createPreSignedUploadRaw(requestParameters: CreatePreSignedUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GeneratePreSignedUrlOutput>> {
        const requestOptions = await this.createPreSignedUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GeneratePreSignedUrlOutputFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 为需要上传的新附件申请对象存储地址。  ### Use case Request an object-storage URL for a new attachment.  ### 前置条件 已计算文件 MD5，文件模块为 ai-chat-attachments。  ### Prerequisites The file MD5 is known and the module is ai-chat-attachments.  ### 行为与副作用 创建短期上传授权，不代表上传完成。  ### Behavior and side effects Creates short-lived upload authorization; upload is not yet complete.  ### 后续调用 按返回 headers 上传文件，再调用确认接口。  ### Next step Upload with the returned headers, then call confirmation.  ### 接口摘要 创建预签名上传地址 / Create a presigned upload URL  ### Operation summary 创建预签名上传地址 / Create a presigned upload URL
     * 创建预签名上传地址 / Create a presigned upload URL
     */
    async createPreSignedUpload(requestParameters: CreatePreSignedUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GeneratePreSignedUrlOutput> {
        const response = await this.createPreSignedUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for fileExistsByContentMd5 without sending the request
     */
    async fileExistsByContentMd5RequestOpts(requestParameters: FileExistsByContentMd5Request): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling fileExistsByContentMd5().'
            );
        }

        if (requestParameters['contentMd5'] == null) {
            throw new runtime.RequiredError(
                'contentMd5',
                'Required parameter "contentMd5" was null or undefined when calling fileExistsByContentMd5().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['contentMd5'] != null) {
            queryParameters['contentMd5'] = requestParameters['contentMd5'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/files/meta/contentMd5`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ### 使用场景 上传前检查相同内容是否已经存在。  ### Use case Check whether identical content exists before uploading.  ### 前置条件 已计算文件 MD5。  ### Prerequisites The file MD5 is known.  ### 行为与副作用 只读。  ### Behavior and side effects Read-only.  ### 后续调用 存在时尝试复用，否则走预签名上传。  ### Next step Attempt reuse when present; otherwise use presigned upload.  ### 接口摘要 检查 MD5 文件是否存在 / Check file existence by MD5  ### Operation summary 检查 MD5 文件是否存在 / Check file existence by MD5
     * 检查 MD5 文件是否存在 / Check file existence by MD5
     */
    async fileExistsByContentMd5Raw(requestParameters: FileExistsByContentMd5Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileExists>> {
        const requestOptions = await this.fileExistsByContentMd5RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileExistsFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 上传前检查相同内容是否已经存在。  ### Use case Check whether identical content exists before uploading.  ### 前置条件 已计算文件 MD5。  ### Prerequisites The file MD5 is known.  ### 行为与副作用 只读。  ### Behavior and side effects Read-only.  ### 后续调用 存在时尝试复用，否则走预签名上传。  ### Next step Attempt reuse when present; otherwise use presigned upload.  ### 接口摘要 检查 MD5 文件是否存在 / Check file existence by MD5  ### Operation summary 检查 MD5 文件是否存在 / Check file existence by MD5
     * 检查 MD5 文件是否存在 / Check file existence by MD5
     */
    async fileExistsByContentMd5(requestParameters: FileExistsByContentMd5Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileExists> {
        const response = await this.fileExistsByContentMd5Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getConversationFilePreview without sending the request
     */
    async getConversationFilePreviewRequestOpts(requestParameters: GetConversationFilePreviewRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getConversationFilePreview().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling getConversationFilePreview().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling getConversationFilePreview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/files/{fileId}/preview`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));
        urlPath = urlPath.replace('{fileId}', encodeURIComponent(String(requestParameters['fileId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ### 使用场景 为会话附件创建短期预览地址。  ### Use case Create a short-lived preview URL for a conversation attachment.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 生成临时读取授权，不修改文件。  ### Behavior and side effects Creates temporary read authorization without changing the file.  ### 后续调用 在过期前打开或下载 URL。  ### Next step Open or download the URL before it expires.  ### 接口摘要 创建会话文件预览地址 / Create a conversation file preview URL  ### Operation summary 创建会话文件预览地址 / Create a conversation file preview URL
     * 创建会话文件预览地址 / Create a conversation file preview URL
     */
    async getConversationFilePreviewRaw(requestParameters: GetConversationFilePreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PreSignedReadUrl>> {
        const requestOptions = await this.getConversationFilePreviewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PreSignedReadUrlFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 为会话附件创建短期预览地址。  ### Use case Create a short-lived preview URL for a conversation attachment.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 生成临时读取授权，不修改文件。  ### Behavior and side effects Creates temporary read authorization without changing the file.  ### 后续调用 在过期前打开或下载 URL。  ### Next step Open or download the URL before it expires.  ### 接口摘要 创建会话文件预览地址 / Create a conversation file preview URL  ### Operation summary 创建会话文件预览地址 / Create a conversation file preview URL
     * 创建会话文件预览地址 / Create a conversation file preview URL
     */
    async getConversationFilePreview(requestParameters: GetConversationFilePreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PreSignedReadUrl> {
        const response = await this.getConversationFilePreviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPlanIntermediateFilePreview without sending the request
     */
    async getPlanIntermediateFilePreviewRequestOpts(requestParameters: GetPlanIntermediateFilePreviewRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getPlanIntermediateFilePreview().'
            );
        }

        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling getPlanIntermediateFilePreview().'
            );
        }

        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling getPlanIntermediateFilePreview().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling getPlanIntermediateFilePreview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-User"] = await this.configuration.apiKey("X-OpenAPI-User"); // OpenApiUser authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-AK"] = await this.configuration.apiKey("X-OpenAPI-AK"); // OpenApiAccessKey authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Timestamp"] = await this.configuration.apiKey("X-OpenAPI-Timestamp"); // OpenApiTimestamp authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Nonce"] = await this.configuration.apiKey("X-OpenAPI-Nonce"); // OpenApiNonce authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-OpenAPI-Signature"] = await this.configuration.apiKey("X-OpenAPI-Signature"); // OpenApiSignature authentication
        }


        let urlPath = `/api/agents/channel/openapi/v1/{channelId}/chat/conversations/{conversationId}/messages/{messageId}/plan-intermediate-files/{fileId}/preview`;
        urlPath = urlPath.replace('{channelId}', encodeURIComponent(String(requestParameters['channelId'])));
        urlPath = urlPath.replace('{conversationId}', encodeURIComponent(String(requestParameters['conversationId'])));
        urlPath = urlPath.replace('{messageId}', encodeURIComponent(String(requestParameters['messageId'])));
        urlPath = urlPath.replace('{fileId}', encodeURIComponent(String(requestParameters['fileId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * ### 使用场景 预览计划执行过程中生成的中间文件。  ### Use case Preview an intermediate file produced during plan execution.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 生成临时读取授权。  ### Behavior and side effects Creates temporary read authorization.  ### 后续调用 在过期前使用 URL，并保留消息上下文。  ### Next step Use the URL before expiry and preserve message context.  ### 接口摘要 创建计划快照预览地址 / Create a plan snapshot preview URL  ### Operation summary 创建计划快照预览地址 / Create a plan snapshot preview URL
     * 创建计划快照预览地址 / Create a plan snapshot preview URL
     */
    async getPlanIntermediateFilePreviewRaw(requestParameters: GetPlanIntermediateFilePreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PreSignedReadUrl>> {
        const requestOptions = await this.getPlanIntermediateFilePreviewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PreSignedReadUrlFromJSON(jsonValue));
    }

    /**
     * ### 使用场景 预览计划执行过程中生成的中间文件。  ### Use case Preview an intermediate file produced during plan execution.  ### 前置条件 渠道凭证和外部用户已配置，目标资源属于当前用户。  ### Prerequisites Channel credentials and the external user are configured, and the target resource belongs to that user.  ### 行为与副作用 生成临时读取授权。  ### Behavior and side effects Creates temporary read authorization.  ### 后续调用 在过期前使用 URL，并保留消息上下文。  ### Next step Use the URL before expiry and preserve message context.  ### 接口摘要 创建计划快照预览地址 / Create a plan snapshot preview URL  ### Operation summary 创建计划快照预览地址 / Create a plan snapshot preview URL
     * 创建计划快照预览地址 / Create a plan snapshot preview URL
     */
    async getPlanIntermediateFilePreview(requestParameters: GetPlanIntermediateFilePreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PreSignedReadUrl> {
        const response = await this.getPlanIntermediateFilePreviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
