/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelConfig } from './ModelConfig';
import {
    ModelConfigFromJSON,
    ModelConfigFromJSONTyped,
    ModelConfigToJSON,
    ModelConfigToJSONTyped,
} from './ModelConfig';
import type { AttachmentExtension } from './AttachmentExtension';
import {
    AttachmentExtensionFromJSON,
    AttachmentExtensionFromJSONTyped,
    AttachmentExtensionToJSON,
    AttachmentExtensionToJSONTyped,
} from './AttachmentExtension';

/**
 * AgentsConfig 的公开协议结构。 / Public contract for agents config.
 * @export
 * @interface AgentsConfig
 */
export interface AgentsConfig {
    /**
     * 字段 modelConfig / model config field。
     */
    modelConfig: ModelConfig;
    /**
     * 字段 supportAttachmentExt / support attachment ext field。
     */
    supportAttachmentExt: Array<AttachmentExtension>;
    /**
     * 字段 maxAttachmentCount / max attachment count field。
     */
    maxAttachmentCount: number;
}

/**
 * Check if a given object implements the AgentsConfig interface.
 */
export function instanceOfAgentsConfig(value: object): value is AgentsConfig {
    if (!('modelConfig' in value) || value['modelConfig'] === undefined) return false;
    if (!('supportAttachmentExt' in value) || value['supportAttachmentExt'] === undefined) return false;
    if (!('maxAttachmentCount' in value) || value['maxAttachmentCount'] === undefined) return false;
    return true;
}

export function AgentsConfigFromJSON(json: any): AgentsConfig {
    return AgentsConfigFromJSONTyped(json, false);
}

export function AgentsConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentsConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'modelConfig': ModelConfigFromJSON(json['modelConfig']),
        'supportAttachmentExt': ((json['supportAttachmentExt'] as Array<any>).map(AttachmentExtensionFromJSON)),
        'maxAttachmentCount': json['maxAttachmentCount'],
    };
}

export function AgentsConfigToJSON(json: any): AgentsConfig {
    return AgentsConfigToJSONTyped(json, false);
}

export function AgentsConfigToJSONTyped(value?: AgentsConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'modelConfig': ModelConfigToJSON(value['modelConfig']),
        'supportAttachmentExt': ((value['supportAttachmentExt'] as Array<any>).map(AttachmentExtensionToJSON)),
        'maxAttachmentCount': value['maxAttachmentCount'],
    };
}

