/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AiChatStartBriefEvent 的公开协议结构。 / Public contract for ai chat start brief event.
 * @export
 * @interface AiChatStartBriefEvent
 */
export interface AiChatStartBriefEvent {
    /**
     * 类型判别值 / type discriminator。
     */
    type: AiChatStartBriefEventTypeEnum;
}


/**
 * @export
 */
export const AiChatStartBriefEventTypeEnum = {
    Start: 'start',
} as const;
export type AiChatStartBriefEventTypeEnum = typeof AiChatStartBriefEventTypeEnum[keyof typeof AiChatStartBriefEventTypeEnum];


/**
 * Check if a given object implements the AiChatStartBriefEvent interface.
 */
export function instanceOfAiChatStartBriefEvent(value: object): value is AiChatStartBriefEvent {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'start') return false;
    
    return true;
}

export function AiChatStartBriefEventFromJSON(json: any): AiChatStartBriefEvent {
    return AiChatStartBriefEventFromJSONTyped(json, false);
}

export function AiChatStartBriefEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatStartBriefEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function AiChatStartBriefEventToJSON(json: any): AiChatStartBriefEvent {
    return AiChatStartBriefEventToJSONTyped(json, false);
}

export function AiChatStartBriefEventToJSONTyped(value?: AiChatStartBriefEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

