/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { AskUserQuestionOption } from './AskUserQuestionOption';
import {
    AskUserQuestionOptionFromJSON,
    AskUserQuestionOptionFromJSONTyped,
    AskUserQuestionOptionToJSON,
    AskUserQuestionOptionToJSONTyped,
} from './AskUserQuestionOption';

/**
 * AiChatAwaitingInputBriefEvent 的公开协议结构。 / Public contract for ai chat awaiting input brief event.
 * @export
 * @interface AiChatAwaitingInputBriefEvent
 */
export interface AiChatAwaitingInputBriefEvent {
    /**
     * 类型判别值 / type discriminator。
     */
    type: AiChatAwaitingInputBriefEventTypeEnum;
    /**
     * 字段 toolCallId / tool call id field。
     */
    toolCallId: string;
    /**
     * 字段 toolName / tool name field。
     */
    toolName: string;
    /**
     * 字段 questionId / question id field。
     */
    questionId: string;
    /**
     * 字段 question / question field。
     */
    question: string;
    /**
     * 字段 options / options field。
     */
    options: Array<AskUserQuestionOption>;
    /**
     * 字段 multiple / multiple field。
     */
    multiple: boolean;
    /**
     * 字段 serverNow / server now field。
     */
    serverNow: Date;
    /**
     * 字段 timeoutSeconds / timeout seconds field。
     */
    timeoutSeconds: number;
    /**
     * 字段 questionDetails / question details field。
     */
    questionDetails?: string | null;
}


/**
 * @export
 */
export const AiChatAwaitingInputBriefEventTypeEnum = {
    ToolExecutionAwaitingUserInput: 'tool-execution-awaiting-user-input',
} as const;
export type AiChatAwaitingInputBriefEventTypeEnum = typeof AiChatAwaitingInputBriefEventTypeEnum[keyof typeof AiChatAwaitingInputBriefEventTypeEnum];


/**
 * Check if a given object implements the AiChatAwaitingInputBriefEvent interface.
 */
export function instanceOfAiChatAwaitingInputBriefEvent(value: object): value is AiChatAwaitingInputBriefEvent {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'tool-execution-awaiting-user-input') return false;
    
    if (!('toolCallId' in value) || value['toolCallId'] === undefined) return false;
    if (!('toolName' in value) || value['toolName'] === undefined) return false;
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('multiple' in value) || value['multiple'] === undefined) return false;
    if (!('serverNow' in value) || value['serverNow'] === undefined) return false;
    if (!('timeoutSeconds' in value) || value['timeoutSeconds'] === undefined) return false;
    return true;
}

export function AiChatAwaitingInputBriefEventFromJSON(json: any): AiChatAwaitingInputBriefEvent {
    return AiChatAwaitingInputBriefEventFromJSONTyped(json, false);
}

export function AiChatAwaitingInputBriefEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatAwaitingInputBriefEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'toolCallId': json['toolCallId'],
        'toolName': json['toolName'],
        'questionId': json['questionId'],
        'question': json['question'],
        'options': ((json['options'] as Array<any>).map(AskUserQuestionOptionFromJSON)),
        'multiple': json['multiple'],
        'serverNow': (json['serverNow'] == null ? json['serverNow'] : parseDateTime(json['serverNow'])),
        'timeoutSeconds': json['timeoutSeconds'],
        'questionDetails': json['questionDetails'] === undefined ? undefined : json['questionDetails'] === null ? null : json['questionDetails'],
    };
}

export function AiChatAwaitingInputBriefEventToJSON(json: any): AiChatAwaitingInputBriefEvent {
    return AiChatAwaitingInputBriefEventToJSONTyped(json, false);
}

export function AiChatAwaitingInputBriefEventToJSONTyped(value?: AiChatAwaitingInputBriefEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'toolCallId': value['toolCallId'],
        'toolName': value['toolName'],
        'questionId': value['questionId'],
        'question': value['question'],
        'options': ((value['options'] as Array<any>).map(AskUserQuestionOptionToJSON)),
        'multiple': value['multiple'],
        'serverNow': value['serverNow'] == null ? value['serverNow'] : serializeDateTime(value['serverNow']),
        'timeoutSeconds': value['timeoutSeconds'],
        'questionDetails': value['questionDetails'],
    };
}

