/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { AskUserQuestionOption } from './AskUserQuestionOption';
import {
    AskUserQuestionOptionFromJSON,
    AskUserQuestionOptionFromJSONTyped,
    AskUserQuestionOptionToJSON,
    AskUserQuestionOptionToJSONTyped,
} from './AskUserQuestionOption';

/**
 * AiChatAwaitingInputBriefEvent 的公开协议结构。 / Public contract for ai chat awaiting input brief event.
 * @export
 * @interface AiChatAwaitingInputBriefEvent
 */
export interface AiChatAwaitingInputBriefEvent {
    /**
     * 类型判别值 / type discriminator。
     */
    type: AiChatAwaitingInputBriefEventTypeEnum;
    /**
     * 字段 toolCallId / tool call id field。
     */
    toolCallId: string;
    /**
     * 字段 toolName / tool name field。
     */
    toolName: string;
    /**
     * 字段 questionId / question id field。
     */
    questionId: string;
    /**
     * 字段 question / question field。
     */
    question: string;
    /**
     * 字段 options / options field。
     */
    options: Array<AskUserQuestionOption>;
    /**
     * 字段 multiple / multiple field。
     */
    multiple: boolean;
    /**
     * 字段 serverNow / server now field。
     */
    serverNow: Date;
    /**
     * 字段 timeoutSeconds / timeout seconds field。
     */
    timeoutSeconds: number;
    /**
     * 字段 questionDetails / question details field。
     */
    questionDetails?: string | null;
}


/**
 * @export
 */
export const AiChatAwaitingInputBriefEventTypeEnum = {
    ToolExecutionAwaitingUserInput: 'tool-execution-awaiting-user-input',
} as const;
export type AiChatAwaitingInputBriefEventTypeEnum = typeof AiChatAwaitingInputBriefEventTypeEnum[keyof typeof AiChatAwaitingInputBriefEventTypeEnum];


/**
 * Check if a given object implements the AiChatAwaitingInputBriefEvent interface.
 */
export function instanceOfAiChatAwaitingInputBriefEvent(value: object): value is AiChatAwaitingInputBriefEvent {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'tool-execution-awaiting-user-input') return false;
    
    if (!('toolCallId' in value) || value['toolCallId'] === undefined) return false;
    if (!('toolName' in value) || value['toolName'] === undefined) return false;
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('multiple' in value) || value['multiple'] === undefined) return false;
    if (!('serverNow' in value) || value['serverNow'] === undefined) return false;
    if (!('timeoutSeconds' in value) || value['timeoutSeconds'] === undefined) return false;
    return true;
}

export function AiChatAwaitingInputBriefEventFromJSON(json: any): AiChatAwaitingInputBriefEvent {
    return AiChatAwaitingInputBriefEventFromJSONTyped(json, false);
}

export function AiChatAwaitingInputBriefEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatAwaitingInputBriefEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'toolCallId': json['toolCallId'],
        'toolName': json['toolName'],
        'questionId': json['questionId'],
        'question': json['question'],
        'options': ((json['options'] as Array<any>).map(AskUserQuestionOptionFromJSON)),
        'multiple': json['multiple'],
        'serverNow': (json['serverNow'] == null ? json['serverNow'] : parseDateTime(json['serverNow'])),
        'timeoutSeconds': json['timeoutSeconds'],
        'questionDetails': json['questionDetails'] === undefined ? undefined : json['questionDetails'] === null ? null : json['questionDetails'],
    };
}

export function AiChatAwaitingInputBriefEventToJSON(json: any): AiChatAwaitingInputBriefEvent {
    return AiChatAwaitingInputBriefEventToJSONTyped(json, false);
}

export function AiChatAwaitingInputBriefEventToJSONTyped(value?: AiChatAwaitingInputBriefEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'toolCallId': value['toolCallId'],
        'toolName': value['toolName'],
        'questionId': value['questionId'],
        'question': value['question'],
        'options': ((value['options'] as Array<any>).map(AskUserQuestionOptionToJSON)),
        'multiple': value['multiple'],
        'serverNow': value['serverNow'] == null ? value['serverNow'] : serializeDateTime(value['serverNow']),
        'timeoutSeconds': value['timeoutSeconds'],
        'questionDetails': value['questionDetails'],
    };
}

