/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AiChatManualInterruptBriefEvent 的公开协议结构。 / Public contract for ai chat manual interrupt brief event.
 * @export
 * @interface AiChatManualInterruptBriefEvent
 */
export interface AiChatManualInterruptBriefEvent {
    /**
     * 类型判别值 / type discriminator。
     */
    type: AiChatManualInterruptBriefEventTypeEnum;
}


/**
 * @export
 */
export const AiChatManualInterruptBriefEventTypeEnum = {
    ManualInterrupt: 'manual-interrupt',
} as const;
export type AiChatManualInterruptBriefEventTypeEnum = typeof AiChatManualInterruptBriefEventTypeEnum[keyof typeof AiChatManualInterruptBriefEventTypeEnum];


/**
 * Check if a given object implements the AiChatManualInterruptBriefEvent interface.
 */
export function instanceOfAiChatManualInterruptBriefEvent(value: object): value is AiChatManualInterruptBriefEvent {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'manual-interrupt') return false;
    
    return true;
}

export function AiChatManualInterruptBriefEventFromJSON(json: any): AiChatManualInterruptBriefEvent {
    return AiChatManualInterruptBriefEventFromJSONTyped(json, false);
}

export function AiChatManualInterruptBriefEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatManualInterruptBriefEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function AiChatManualInterruptBriefEventToJSON(json: any): AiChatManualInterruptBriefEvent {
    return AiChatManualInterruptBriefEventToJSONTyped(json, false);
}

export function AiChatManualInterruptBriefEventToJSONTyped(value?: AiChatManualInterruptBriefEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

