/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AiChatEventsBatchInput 的公开协议结构。 / Public contract for ai chat events batch input.
 * @export
 * @interface AiChatEventsBatchInput
 */
export interface AiChatEventsBatchInput {
    /**
     * 会话 ID / conversation ID。
     */
    conversationId: string;
    /**
     * 字段 messageIds / message ids field。
     */
    messageIds: Array<string>;
}

/**
 * Check if a given object implements the AiChatEventsBatchInput interface.
 */
export function instanceOfAiChatEventsBatchInput(value: object): value is AiChatEventsBatchInput {
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('messageIds' in value) || value['messageIds'] === undefined) return false;
    return true;
}

export function AiChatEventsBatchInputFromJSON(json: any): AiChatEventsBatchInput {
    return AiChatEventsBatchInputFromJSONTyped(json, false);
}

export function AiChatEventsBatchInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatEventsBatchInput {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationId': json['conversationId'],
        'messageIds': json['messageIds'],
    };
}

export function AiChatEventsBatchInputToJSON(json: any): AiChatEventsBatchInput {
    return AiChatEventsBatchInputToJSONTyped(json, false);
}

export function AiChatEventsBatchInputToJSONTyped(value?: AiChatEventsBatchInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversationId': value['conversationId'],
        'messageIds': value['messageIds'],
    };
}

