/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AiChatSubAgentCallBriefEvent 的公开协议结构。 / Public contract for ai chat sub agent call brief event.
 * @export
 * @interface AiChatSubAgentCallBriefEvent
 */
export interface AiChatSubAgentCallBriefEvent {
    /**
     * 类型判别值 / type discriminator。
     */
    type: AiChatSubAgentCallBriefEventTypeEnum;
    /**
     * 字段 toolCallId / tool call id field。
     */
    toolCallId: string;
    /**
     * 字段 toolName / tool name field。
     */
    toolName: string;
    /**
     * 字段 subAgentConversationId / sub agent conversation id field。
     */
    subAgentConversationId: string;
    /**
     * 字段 subAgentMessageId / sub agent message id field。
     */
    subAgentMessageId: string;
}


/**
 * @export
 */
export const AiChatSubAgentCallBriefEventTypeEnum = {
    ToolExecutionSubAgentCall: 'tool-execution-sub-agent-call',
} as const;
export type AiChatSubAgentCallBriefEventTypeEnum = typeof AiChatSubAgentCallBriefEventTypeEnum[keyof typeof AiChatSubAgentCallBriefEventTypeEnum];


/**
 * Check if a given object implements the AiChatSubAgentCallBriefEvent interface.
 */
export function instanceOfAiChatSubAgentCallBriefEvent(value: object): value is AiChatSubAgentCallBriefEvent {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'tool-execution-sub-agent-call') return false;
    
    if (!('toolCallId' in value) || value['toolCallId'] === undefined) return false;
    if (!('toolName' in value) || value['toolName'] === undefined) return false;
    if (!('subAgentConversationId' in value) || value['subAgentConversationId'] === undefined) return false;
    if (!('subAgentMessageId' in value) || value['subAgentMessageId'] === undefined) return false;
    return true;
}

export function AiChatSubAgentCallBriefEventFromJSON(json: any): AiChatSubAgentCallBriefEvent {
    return AiChatSubAgentCallBriefEventFromJSONTyped(json, false);
}

export function AiChatSubAgentCallBriefEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatSubAgentCallBriefEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'toolCallId': json['toolCallId'],
        'toolName': json['toolName'],
        'subAgentConversationId': json['subAgentConversationId'],
        'subAgentMessageId': json['subAgentMessageId'],
    };
}

export function AiChatSubAgentCallBriefEventToJSON(json: any): AiChatSubAgentCallBriefEvent {
    return AiChatSubAgentCallBriefEventToJSONTyped(json, false);
}

export function AiChatSubAgentCallBriefEventToJSONTyped(value?: AiChatSubAgentCallBriefEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'toolCallId': value['toolCallId'],
        'toolName': value['toolName'],
        'subAgentConversationId': value['subAgentConversationId'],
        'subAgentMessageId': value['subAgentMessageId'],
    };
}

