/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AiChatFileRef 的公开协议结构。 / Public contract for ai chat file ref.
 * @export
 * @interface AiChatFileRef
 */
export interface AiChatFileRef {
    /**
     * 字段 id / id field。
     */
    id: number;
    /**
     * 文件名 / file name。
     */
    fileName?: string | null;
}

/**
 * Check if a given object implements the AiChatFileRef interface.
 */
export function instanceOfAiChatFileRef(value: object): value is AiChatFileRef {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AiChatFileRefFromJSON(json: any): AiChatFileRef {
    return AiChatFileRefFromJSONTyped(json, false);
}

export function AiChatFileRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatFileRef {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'fileName': json['fileName'] === undefined ? undefined : json['fileName'] === null ? null : json['fileName'],
    };
}

export function AiChatFileRefToJSON(json: any): AiChatFileRef {
    return AiChatFileRefToJSONTyped(json, false);
}

export function AiChatFileRefToJSONTyped(value?: AiChatFileRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fileName': value['fileName'],
    };
}

