/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Usage } from './Usage';
import {
    UsageFromJSON,
    UsageFromJSONTyped,
    UsageToJSON,
    UsageToJSONTyped,
} from './Usage';
import type { ArtifactInfo } from './ArtifactInfo';
import {
    ArtifactInfoFromJSON,
    ArtifactInfoFromJSONTyped,
    ArtifactInfoToJSON,
    ArtifactInfoToJSONTyped,
} from './ArtifactInfo';
import type { WorkspaceNonFileArtifact } from './WorkspaceNonFileArtifact';
import {
    WorkspaceNonFileArtifactFromJSON,
    WorkspaceNonFileArtifactFromJSONTyped,
    WorkspaceNonFileArtifactToJSON,
    WorkspaceNonFileArtifactToJSONTyped,
} from './WorkspaceNonFileArtifact';
import type { ConversationContextUsage } from './ConversationContextUsage';
import {
    ConversationContextUsageFromJSON,
    ConversationContextUsageFromJSONTyped,
    ConversationContextUsageToJSON,
    ConversationContextUsageToJSONTyped,
} from './ConversationContextUsage';

/**
 * AiChatEndBriefEvent 的公开协议结构。 / Public contract for ai chat end brief event.
 * @export
 * @interface AiChatEndBriefEvent
 */
export interface AiChatEndBriefEvent {
    /**
     * 类型判别值 / type discriminator。
     */
    type: AiChatEndBriefEventTypeEnum;
    /**
     * 字段 executionTimeMillis / execution time millis field。
     */
    executionTimeMillis: number;
    /**
     * 字段 totalUsage / total usage field。
     */
    totalUsage: Usage;
    /**
     * 字段 messageContextUsageRatio / message context usage ratio field。
     */
    messageContextUsageRatio?: number | null;
    /**
     * 字段 contextWindowUsage / context window usage field。
     */
    contextWindowUsage?: ConversationContextUsage | null;
    /**
     * 字段 artifacts / artifacts field。
     */
    artifacts: Array<ArtifactInfo>;
    /**
     * 字段 nonFileArtifacts / non file artifacts field。
     */
    nonFileArtifacts: Array<WorkspaceNonFileArtifact>;
}


/**
 * @export
 */
export const AiChatEndBriefEventTypeEnum = {
    End: 'end',
} as const;
export type AiChatEndBriefEventTypeEnum = typeof AiChatEndBriefEventTypeEnum[keyof typeof AiChatEndBriefEventTypeEnum];


/**
 * Check if a given object implements the AiChatEndBriefEvent interface.
 */
export function instanceOfAiChatEndBriefEvent(value: object): value is AiChatEndBriefEvent {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'end') return false;
    
    if (!('executionTimeMillis' in value) || value['executionTimeMillis'] === undefined) return false;
    if (!('totalUsage' in value) || value['totalUsage'] === undefined) return false;
    if (!('artifacts' in value) || value['artifacts'] === undefined) return false;
    if (!('nonFileArtifacts' in value) || value['nonFileArtifacts'] === undefined) return false;
    return true;
}

export function AiChatEndBriefEventFromJSON(json: any): AiChatEndBriefEvent {
    return AiChatEndBriefEventFromJSONTyped(json, false);
}

export function AiChatEndBriefEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatEndBriefEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'executionTimeMillis': json['executionTimeMillis'],
        'totalUsage': UsageFromJSON(json['totalUsage']),
        'messageContextUsageRatio': json['messageContextUsageRatio'] === undefined ? undefined : json['messageContextUsageRatio'] === null ? null : json['messageContextUsageRatio'],
        'contextWindowUsage': json['contextWindowUsage'] === undefined ? undefined : json['contextWindowUsage'] === null ? null : ConversationContextUsageFromJSON(json['contextWindowUsage']),
        'artifacts': ((json['artifacts'] as Array<any>).map(ArtifactInfoFromJSON)),
        'nonFileArtifacts': ((json['nonFileArtifacts'] as Array<any>).map(WorkspaceNonFileArtifactFromJSON)),
    };
}

export function AiChatEndBriefEventToJSON(json: any): AiChatEndBriefEvent {
    return AiChatEndBriefEventToJSONTyped(json, false);
}

export function AiChatEndBriefEventToJSONTyped(value?: AiChatEndBriefEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'executionTimeMillis': value['executionTimeMillis'],
        'totalUsage': UsageToJSON(value['totalUsage']),
        'messageContextUsageRatio': value['messageContextUsageRatio'],
        'contextWindowUsage': ConversationContextUsageToJSON(value['contextWindowUsage']),
        'artifacts': ((value['artifacts'] as Array<any>).map(ArtifactInfoToJSON)),
        'nonFileArtifacts': ((value['nonFileArtifacts'] as Array<any>).map(WorkspaceNonFileArtifactToJSON)),
    };
}

