/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolExtension } from './ToolExtension';
import {
    ToolExtensionFromJSON,
    ToolExtensionFromJSONTyped,
    ToolExtensionToJSON,
    ToolExtensionToJSONTyped,
} from './ToolExtension';

/**
 * AiChatToolExecutionBriefEvent 的公开协议结构。 / Public contract for ai chat tool execution brief event.
 * @export
 * @interface AiChatToolExecutionBriefEvent
 */
export interface AiChatToolExecutionBriefEvent {
    /**
     * 类型判别值 / type discriminator。
     */
    type: AiChatToolExecutionBriefEventTypeEnum;
    /**
     * 字段 toolId / tool id field。
     */
    toolId: string;
    /**
     * 字段 toolName / tool name field。
     */
    toolName: string;
    /**
     * 当前状态 / current status。
     */
    status: string;
    /**
     * 字段 action / action field。
     */
    action: string;
    /**
     * 字段 summary / summary field。
     */
    summary?: string | null;
    /**
     * 字段 extension / extension field。
     */
    extension?: ToolExtension | null;
}


/**
 * @export
 */
export const AiChatToolExecutionBriefEventTypeEnum = {
    ToolExecution: 'tool-execution',
} as const;
export type AiChatToolExecutionBriefEventTypeEnum = typeof AiChatToolExecutionBriefEventTypeEnum[keyof typeof AiChatToolExecutionBriefEventTypeEnum];


/**
 * Check if a given object implements the AiChatToolExecutionBriefEvent interface.
 */
export function instanceOfAiChatToolExecutionBriefEvent(value: object): value is AiChatToolExecutionBriefEvent {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'tool-execution') return false;
    
    if (!('toolId' in value) || value['toolId'] === undefined) return false;
    if (!('toolName' in value) || value['toolName'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function AiChatToolExecutionBriefEventFromJSON(json: any): AiChatToolExecutionBriefEvent {
    return AiChatToolExecutionBriefEventFromJSONTyped(json, false);
}

export function AiChatToolExecutionBriefEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatToolExecutionBriefEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'toolId': json['toolId'],
        'toolName': json['toolName'],
        'status': json['status'],
        'action': json['action'],
        'summary': json['summary'] === undefined ? undefined : json['summary'] === null ? null : json['summary'],
        'extension': json['extension'] === undefined ? undefined : json['extension'] === null ? null : ToolExtensionFromJSON(json['extension']),
    };
}

export function AiChatToolExecutionBriefEventToJSON(json: any): AiChatToolExecutionBriefEvent {
    return AiChatToolExecutionBriefEventToJSONTyped(json, false);
}

export function AiChatToolExecutionBriefEventToJSONTyped(value?: AiChatToolExecutionBriefEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'toolId': value['toolId'],
        'toolName': value['toolName'],
        'status': value['status'],
        'action': value['action'],
        'summary': value['summary'],
        'extension': ToolExtensionToJSON(value['extension']),
    };
}

