/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AiChatSubmission 的公开协议结构。 / Public contract for ai chat submission.
 * @export
 * @interface AiChatSubmission
 */
export interface AiChatSubmission {
    /**
     * 会话 ID / conversation ID。
     */
    conversationId: string;
    /**
     * 消息 ID / message ID。
     */
    messageId: string;
    /**
     * 字段 disposition / disposition field。 Dispatch disposition. Unknown future values must be preserved.
     */
    disposition: string;
    /**
     * 当前状态 / current status。 Persisted message status. Unknown future values must be preserved.
     */
    status: string;
}

/**
 * Check if a given object implements the AiChatSubmission interface.
 */
export function instanceOfAiChatSubmission(value: object): value is AiChatSubmission {
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('disposition' in value) || value['disposition'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AiChatSubmissionFromJSON(json: any): AiChatSubmission {
    return AiChatSubmissionFromJSONTyped(json, false);
}

export function AiChatSubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatSubmission {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationId': json['conversationId'],
        'messageId': json['messageId'],
        'disposition': json['disposition'],
        'status': json['status'],
    };
}

export function AiChatSubmissionToJSON(json: any): AiChatSubmission {
    return AiChatSubmissionToJSONTyped(json, false);
}

export function AiChatSubmissionToJSONTyped(value?: AiChatSubmission | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversationId': value['conversationId'],
        'messageId': value['messageId'],
        'disposition': value['disposition'],
        'status': value['status'],
    };
}

