/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Usage } from './Usage';
import {
    UsageFromJSON,
    UsageFromJSONTyped,
    UsageToJSON,
    UsageToJSONTyped,
} from './Usage';
import type { ArtifactInfo } from './ArtifactInfo';
import {
    ArtifactInfoFromJSON,
    ArtifactInfoFromJSONTyped,
    ArtifactInfoToJSON,
    ArtifactInfoToJSONTyped,
} from './ArtifactInfo';
import type { WorkspaceNonFileArtifact } from './WorkspaceNonFileArtifact';
import {
    WorkspaceNonFileArtifactFromJSON,
    WorkspaceNonFileArtifactFromJSONTyped,
    WorkspaceNonFileArtifactToJSON,
    WorkspaceNonFileArtifactToJSONTyped,
} from './WorkspaceNonFileArtifact';
import type { ConversationContextUsage } from './ConversationContextUsage';
import {
    ConversationContextUsageFromJSON,
    ConversationContextUsageFromJSONTyped,
    ConversationContextUsageToJSON,
    ConversationContextUsageToJSONTyped,
} from './ConversationContextUsage';

/**
 * AiChatEndBriefEvent 的公开协议结构。 / Public contract for ai chat end brief event.
 * @export
 * @interface AiChatEndBriefEvent
 */
export interface AiChatEndBriefEvent {
    /**
     * 类型判别值 / type discriminator。
     */
    type: AiChatEndBriefEventTypeEnum;
    /**
     * 字段 executionTimeMillis / execution time millis field。
     */
    executionTimeMillis: number;
    /**
     * 字段 totalUsage / total usage field。
     */
    totalUsage: Usage;
    /**
     * 字段 messageContextUsageRatio / message context usage ratio field。
     */
    messageContextUsageRatio?: number | null;
    /**
     * 字段 contextWindowUsage / context window usage field。
     */
    contextWindowUsage?: ConversationContextUsage | null;
    /**
     * 字段 artifacts / artifacts field。
     */
    artifacts: Array<ArtifactInfo>;
    /**
     * 字段 nonFileArtifacts / non file artifacts field。
     */
    nonFileArtifacts: Array<WorkspaceNonFileArtifact>;
}


/**
 * @export
 */
export const AiChatEndBriefEventTypeEnum = {
    End: 'end',
} as const;
export type AiChatEndBriefEventTypeEnum = typeof AiChatEndBriefEventTypeEnum[keyof typeof AiChatEndBriefEventTypeEnum];


/**
 * Check if a given object implements the AiChatEndBriefEvent interface.
 */
export function instanceOfAiChatEndBriefEvent(value: object): value is AiChatEndBriefEvent {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'end') return false;
    
    if (!('executionTimeMillis' in value) || value['executionTimeMillis'] === undefined) return false;
    if (!('totalUsage' in value) || value['totalUsage'] === undefined) return false;
    if (!('artifacts' in value) || value['artifacts'] === undefined) return false;
    if (!('nonFileArtifacts' in value) || value['nonFileArtifacts'] === undefined) return false;
    return true;
}

export function AiChatEndBriefEventFromJSON(json: any): AiChatEndBriefEvent {
    return AiChatEndBriefEventFromJSONTyped(json, false);
}

export function AiChatEndBriefEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatEndBriefEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'executionTimeMillis': json['executionTimeMillis'],
        'totalUsage': UsageFromJSON(json['totalUsage']),
        'messageContextUsageRatio': json['messageContextUsageRatio'] === undefined ? undefined : json['messageContextUsageRatio'] === null ? null : json['messageContextUsageRatio'],
        'contextWindowUsage': json['contextWindowUsage'] === undefined ? undefined : json['contextWindowUsage'] === null ? null : ConversationContextUsageFromJSON(json['contextWindowUsage']),
        'artifacts': ((json['artifacts'] as Array<any>).map(ArtifactInfoFromJSON)),
        'nonFileArtifacts': ((json['nonFileArtifacts'] as Array<any>).map(WorkspaceNonFileArtifactFromJSON)),
    };
}

export function AiChatEndBriefEventToJSON(json: any): AiChatEndBriefEvent {
    return AiChatEndBriefEventToJSONTyped(json, false);
}

export function AiChatEndBriefEventToJSONTyped(value?: AiChatEndBriefEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'executionTimeMillis': value['executionTimeMillis'],
        'totalUsage': UsageToJSON(value['totalUsage']),
        'messageContextUsageRatio': value['messageContextUsageRatio'],
        'contextWindowUsage': ConversationContextUsageToJSON(value['contextWindowUsage']),
        'artifacts': ((value['artifacts'] as Array<any>).map(ArtifactInfoToJSON)),
        'nonFileArtifacts': ((value['nonFileArtifacts'] as Array<any>).map(WorkspaceNonFileArtifactToJSON)),
    };
}

