/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatModelSpec } from './ChatModelSpec';
import {
    ChatModelSpecFromJSON,
    ChatModelSpecFromJSONTyped,
    ChatModelSpecToJSON,
    ChatModelSpecToJSONTyped,
} from './ChatModelSpec';
import type { AiChatFileRef } from './AiChatFileRef';
import {
    AiChatFileRefFromJSON,
    AiChatFileRefFromJSONTyped,
    AiChatFileRefToJSON,
    AiChatFileRefToJSONTyped,
} from './AiChatFileRef';

/**
 * AiChatInput 的公开协议结构。 / Public contract for ai chat input.
 * @export
 * @interface AiChatInput
 */
export interface AiChatInput {
    /**
     * 用户问题 / user query。
     */
    query: string;
    /**
     * 会话 ID / conversation ID。
     */
    conversationId?: string | null;
    /**
     * 字段 chatModelSpec / chat model spec field。
     */
    chatModelSpec?: ChatModelSpec | null;
    /**
     * 字段 files / files field。
     */
    files?: Array<AiChatFileRef> | null;
}

/**
 * Check if a given object implements the AiChatInput interface.
 */
export function instanceOfAiChatInput(value: object): value is AiChatInput {
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function AiChatInputFromJSON(json: any): AiChatInput {
    return AiChatInputFromJSONTyped(json, false);
}

export function AiChatInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatInput {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'],
        'conversationId': json['conversationId'] === undefined ? undefined : json['conversationId'] === null ? null : json['conversationId'],
        'chatModelSpec': json['chatModelSpec'] === undefined ? undefined : json['chatModelSpec'] === null ? null : ChatModelSpecFromJSON(json['chatModelSpec']),
        'files': json['files'] === undefined ? undefined : json['files'] === null ? null : ((json['files'] as Array<any>).map(AiChatFileRefFromJSON)),
    };
}

export function AiChatInputToJSON(json: any): AiChatInput {
    return AiChatInputToJSONTyped(json, false);
}

export function AiChatInputToJSONTyped(value?: AiChatInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
        'conversationId': value['conversationId'],
        'chatModelSpec': ChatModelSpecToJSON(value['chatModelSpec']),
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(AiChatFileRefToJSON)),
    };
}

