/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiChatBriefEvent } from './AiChatBriefEvent';
import {
    AiChatBriefEventFromJSON,
    AiChatBriefEventFromJSONTyped,
    AiChatBriefEventToJSON,
    AiChatBriefEventToJSONTyped,
} from './AiChatBriefEvent';

/**
 * AiChatBriefEventList 的公开协议结构。 / Public contract for ai chat brief event list.
 * @export
 * @interface AiChatBriefEventList
 */
export interface AiChatBriefEventList {
    /**
     * 记录列表 / records。
     */
    records: Array<AiChatBriefEvent>;
}

/**
 * Check if a given object implements the AiChatBriefEventList interface.
 */
export function instanceOfAiChatBriefEventList(value: object): value is AiChatBriefEventList {
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function AiChatBriefEventListFromJSON(json: any): AiChatBriefEventList {
    return AiChatBriefEventListFromJSONTyped(json, false);
}

export function AiChatBriefEventListFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatBriefEventList {
    if (json == null) {
        return json;
    }
    return {
        
        'records': ((json['records'] as Array<any>).map(AiChatBriefEventFromJSON)),
    };
}

export function AiChatBriefEventListToJSON(json: any): AiChatBriefEventList {
    return AiChatBriefEventListToJSONTyped(json, false);
}

export function AiChatBriefEventListToJSONTyped(value?: AiChatBriefEventList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'records': ((value['records'] as Array<any>).map(AiChatBriefEventToJSON)),
    };
}

