/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { AiChatAwaitingInputBriefEvent } from './AiChatAwaitingInputBriefEvent';
import {
    instanceOfAiChatAwaitingInputBriefEvent,
    AiChatAwaitingInputBriefEventFromJSON,
    AiChatAwaitingInputBriefEventFromJSONTyped,
    AiChatAwaitingInputBriefEventToJSON,
} from './AiChatAwaitingInputBriefEvent';
import type { AiChatCompactorWarningBriefEvent } from './AiChatCompactorWarningBriefEvent';
import {
    instanceOfAiChatCompactorWarningBriefEvent,
    AiChatCompactorWarningBriefEventFromJSON,
    AiChatCompactorWarningBriefEventFromJSONTyped,
    AiChatCompactorWarningBriefEventToJSON,
} from './AiChatCompactorWarningBriefEvent';
import type { AiChatCompressorContextEndBriefEvent } from './AiChatCompressorContextEndBriefEvent';
import {
    instanceOfAiChatCompressorContextEndBriefEvent,
    AiChatCompressorContextEndBriefEventFromJSON,
    AiChatCompressorContextEndBriefEventFromJSONTyped,
    AiChatCompressorContextEndBriefEventToJSON,
} from './AiChatCompressorContextEndBriefEvent';
import type { AiChatCompressorContextStartBriefEvent } from './AiChatCompressorContextStartBriefEvent';
import {
    instanceOfAiChatCompressorContextStartBriefEvent,
    AiChatCompressorContextStartBriefEventFromJSON,
    AiChatCompressorContextStartBriefEventFromJSONTyped,
    AiChatCompressorContextStartBriefEventToJSON,
} from './AiChatCompressorContextStartBriefEvent';
import type { AiChatEndBriefEvent } from './AiChatEndBriefEvent';
import {
    instanceOfAiChatEndBriefEvent,
    AiChatEndBriefEventFromJSON,
    AiChatEndBriefEventFromJSONTyped,
    AiChatEndBriefEventToJSON,
} from './AiChatEndBriefEvent';
import type { AiChatErrorBriefEvent } from './AiChatErrorBriefEvent';
import {
    instanceOfAiChatErrorBriefEvent,
    AiChatErrorBriefEventFromJSON,
    AiChatErrorBriefEventFromJSONTyped,
    AiChatErrorBriefEventToJSON,
} from './AiChatErrorBriefEvent';
import type { AiChatManualInterruptBriefEvent } from './AiChatManualInterruptBriefEvent';
import {
    instanceOfAiChatManualInterruptBriefEvent,
    AiChatManualInterruptBriefEventFromJSON,
    AiChatManualInterruptBriefEventFromJSONTyped,
    AiChatManualInterruptBriefEventToJSON,
} from './AiChatManualInterruptBriefEvent';
import type { AiChatMessageBriefEvent } from './AiChatMessageBriefEvent';
import {
    instanceOfAiChatMessageBriefEvent,
    AiChatMessageBriefEventFromJSON,
    AiChatMessageBriefEventFromJSONTyped,
    AiChatMessageBriefEventToJSON,
} from './AiChatMessageBriefEvent';
import type { AiChatRequestBriefEvent } from './AiChatRequestBriefEvent';
import {
    instanceOfAiChatRequestBriefEvent,
    AiChatRequestBriefEventFromJSON,
    AiChatRequestBriefEventFromJSONTyped,
    AiChatRequestBriefEventToJSON,
} from './AiChatRequestBriefEvent';
import type { AiChatResponseBriefEvent } from './AiChatResponseBriefEvent';
import {
    instanceOfAiChatResponseBriefEvent,
    AiChatResponseBriefEventFromJSON,
    AiChatResponseBriefEventFromJSONTyped,
    AiChatResponseBriefEventToJSON,
} from './AiChatResponseBriefEvent';
import type { AiChatStartBriefEvent } from './AiChatStartBriefEvent';
import {
    instanceOfAiChatStartBriefEvent,
    AiChatStartBriefEventFromJSON,
    AiChatStartBriefEventFromJSONTyped,
    AiChatStartBriefEventToJSON,
} from './AiChatStartBriefEvent';
import type { AiChatSubAgentCallBriefEvent } from './AiChatSubAgentCallBriefEvent';
import {
    instanceOfAiChatSubAgentCallBriefEvent,
    AiChatSubAgentCallBriefEventFromJSON,
    AiChatSubAgentCallBriefEventFromJSONTyped,
    AiChatSubAgentCallBriefEventToJSON,
} from './AiChatSubAgentCallBriefEvent';
import type { AiChatThinkBriefEvent } from './AiChatThinkBriefEvent';
import {
    instanceOfAiChatThinkBriefEvent,
    AiChatThinkBriefEventFromJSON,
    AiChatThinkBriefEventFromJSONTyped,
    AiChatThinkBriefEventToJSON,
} from './AiChatThinkBriefEvent';
import type { AiChatToolExecutionBriefEvent } from './AiChatToolExecutionBriefEvent';
import {
    instanceOfAiChatToolExecutionBriefEvent,
    AiChatToolExecutionBriefEventFromJSON,
    AiChatToolExecutionBriefEventFromJSONTyped,
    AiChatToolExecutionBriefEventToJSON,
} from './AiChatToolExecutionBriefEvent';
import type { AiChatUserQueryBriefEvent } from './AiChatUserQueryBriefEvent';
import {
    instanceOfAiChatUserQueryBriefEvent,
    AiChatUserQueryBriefEventFromJSON,
    AiChatUserQueryBriefEventFromJSONTyped,
    AiChatUserQueryBriefEventToJSON,
} from './AiChatUserQueryBriefEvent';
import type { UnknownAiChatBriefEvent } from './UnknownAiChatBriefEvent';
import {
    instanceOfUnknownAiChatBriefEvent,
    UnknownAiChatBriefEventFromJSON,
    UnknownAiChatBriefEventFromJSONTyped,
    UnknownAiChatBriefEventToJSON,
} from './UnknownAiChatBriefEvent';

/**
 * @type AiChatBriefEvent
 * AiChatBriefEvent 的公开协议结构。 / Public contract for ai chat brief event.
 * @export
 */
export type AiChatBriefEvent = { type: 'chat-client-request' } & AiChatRequestBriefEvent | { type: 'chat-client-response' } & AiChatResponseBriefEvent | { type: 'compactor-warning' } & AiChatCompactorWarningBriefEvent | { type: 'compressor-context-end' } & AiChatCompressorContextEndBriefEvent | { type: 'compressor-context-start' } & AiChatCompressorContextStartBriefEvent | { type: 'end' } & AiChatEndBriefEvent | { type: 'error' } & AiChatErrorBriefEvent | { type: 'manual-interrupt' } & AiChatManualInterruptBriefEvent | { type: 'message' } & AiChatMessageBriefEvent | { type: 'start' } & AiChatStartBriefEvent | { type: 'think' } & AiChatThinkBriefEvent | { type: 'tool-execution' } & AiChatToolExecutionBriefEvent | { type: 'tool-execution-awaiting-user-input' } & AiChatAwaitingInputBriefEvent | { type: 'tool-execution-sub-agent-call' } & AiChatSubAgentCallBriefEvent | { type: 'user-query' } & AiChatUserQueryBriefEvent;

export function AiChatBriefEventFromJSON(json: any): AiChatBriefEvent {
    return AiChatBriefEventFromJSONTyped(json, false);
}

export function AiChatBriefEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatBriefEvent {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'chat-client-request':
            return Object.assign({}, AiChatRequestBriefEventFromJSONTyped(json, true), { type: 'chat-client-request' } as const);
        case 'chat-client-response':
            return Object.assign({}, AiChatResponseBriefEventFromJSONTyped(json, true), { type: 'chat-client-response' } as const);
        case 'compactor-warning':
            return Object.assign({}, AiChatCompactorWarningBriefEventFromJSONTyped(json, true), { type: 'compactor-warning' } as const);
        case 'compressor-context-end':
            return Object.assign({}, AiChatCompressorContextEndBriefEventFromJSONTyped(json, true), { type: 'compressor-context-end' } as const);
        case 'compressor-context-start':
            return Object.assign({}, AiChatCompressorContextStartBriefEventFromJSONTyped(json, true), { type: 'compressor-context-start' } as const);
        case 'end':
            return Object.assign({}, AiChatEndBriefEventFromJSONTyped(json, true), { type: 'end' } as const);
        case 'error':
            return Object.assign({}, AiChatErrorBriefEventFromJSONTyped(json, true), { type: 'error' } as const);
        case 'manual-interrupt':
            return Object.assign({}, AiChatManualInterruptBriefEventFromJSONTyped(json, true), { type: 'manual-interrupt' } as const);
        case 'message':
            return Object.assign({}, AiChatMessageBriefEventFromJSONTyped(json, true), { type: 'message' } as const);
        case 'start':
            return Object.assign({}, AiChatStartBriefEventFromJSONTyped(json, true), { type: 'start' } as const);
        case 'think':
            return Object.assign({}, AiChatThinkBriefEventFromJSONTyped(json, true), { type: 'think' } as const);
        case 'tool-execution':
            return Object.assign({}, AiChatToolExecutionBriefEventFromJSONTyped(json, true), { type: 'tool-execution' } as const);
        case 'tool-execution-awaiting-user-input':
            return Object.assign({}, AiChatAwaitingInputBriefEventFromJSONTyped(json, true), { type: 'tool-execution-awaiting-user-input' } as const);
        case 'tool-execution-sub-agent-call':
            return Object.assign({}, AiChatSubAgentCallBriefEventFromJSONTyped(json, true), { type: 'tool-execution-sub-agent-call' } as const);
        case 'user-query':
            return Object.assign({}, AiChatUserQueryBriefEventFromJSONTyped(json, true), { type: 'user-query' } as const);
        default:
            return json;
    }
}

export function AiChatBriefEventToJSON(json: any): any {
    return AiChatBriefEventToJSONTyped(json, false);
}

export function AiChatBriefEventToJSONTyped(value?: AiChatBriefEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'chat-client-request':
            return Object.assign({}, AiChatRequestBriefEventToJSON(value), { 'type': 'chat-client-request' } as const);
        case 'chat-client-response':
            return Object.assign({}, AiChatResponseBriefEventToJSON(value), { 'type': 'chat-client-response' } as const);
        case 'compactor-warning':
            return Object.assign({}, AiChatCompactorWarningBriefEventToJSON(value), { 'type': 'compactor-warning' } as const);
        case 'compressor-context-end':
            return Object.assign({}, AiChatCompressorContextEndBriefEventToJSON(value), { 'type': 'compressor-context-end' } as const);
        case 'compressor-context-start':
            return Object.assign({}, AiChatCompressorContextStartBriefEventToJSON(value), { 'type': 'compressor-context-start' } as const);
        case 'end':
            return Object.assign({}, AiChatEndBriefEventToJSON(value), { 'type': 'end' } as const);
        case 'error':
            return Object.assign({}, AiChatErrorBriefEventToJSON(value), { 'type': 'error' } as const);
        case 'manual-interrupt':
            return Object.assign({}, AiChatManualInterruptBriefEventToJSON(value), { 'type': 'manual-interrupt' } as const);
        case 'message':
            return Object.assign({}, AiChatMessageBriefEventToJSON(value), { 'type': 'message' } as const);
        case 'start':
            return Object.assign({}, AiChatStartBriefEventToJSON(value), { 'type': 'start' } as const);
        case 'think':
            return Object.assign({}, AiChatThinkBriefEventToJSON(value), { 'type': 'think' } as const);
        case 'tool-execution':
            return Object.assign({}, AiChatToolExecutionBriefEventToJSON(value), { 'type': 'tool-execution' } as const);
        case 'tool-execution-awaiting-user-input':
            return Object.assign({}, AiChatAwaitingInputBriefEventToJSON(value), { 'type': 'tool-execution-awaiting-user-input' } as const);
        case 'tool-execution-sub-agent-call':
            return Object.assign({}, AiChatSubAgentCallBriefEventToJSON(value), { 'type': 'tool-execution-sub-agent-call' } as const);
        case 'user-query':
            return Object.assign({}, AiChatUserQueryBriefEventToJSON(value), { 'type': 'user-query' } as const);
        default:
            return value;
    }
}

