/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ArtifactInfo 的公开协议结构。 / Public contract for artifact info.
 * @export
 * @interface ArtifactInfo
 */
export interface ArtifactInfo {
    /**
     * 文件 ID / file ID。
     */
    fileId: number;
    /**
     * 字段 fileSize / file size field。
     */
    fileSize: number;
    /**
     * 文件名 / file name。
     */
    fileName: string;
    /**
     * MIME 类型 / MIME type。
     */
    mimeType: string;
    /**
     * 字段 relativePath / relative path field。
     */
    relativePath?: string | null;
    /**
     * 字段 deliveryStatus / delivery status field。
     */
    deliveryStatus: string;
    /**
     * 字段 issueCodes / issue codes field。
     */
    issueCodes: Array<string>;
    /**
     * 字段 recoverable / recoverable field。
     */
    recoverable: boolean;
}

/**
 * Check if a given object implements the ArtifactInfo interface.
 */
export function instanceOfArtifactInfo(value: object): value is ArtifactInfo {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    if (!('fileSize' in value) || value['fileSize'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('deliveryStatus' in value) || value['deliveryStatus'] === undefined) return false;
    if (!('issueCodes' in value) || value['issueCodes'] === undefined) return false;
    if (!('recoverable' in value) || value['recoverable'] === undefined) return false;
    return true;
}

export function ArtifactInfoFromJSON(json: any): ArtifactInfo {
    return ArtifactInfoFromJSONTyped(json, false);
}

export function ArtifactInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtifactInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['fileId'],
        'fileSize': json['fileSize'],
        'fileName': json['fileName'],
        'mimeType': json['mimeType'],
        'relativePath': json['relativePath'] === undefined ? undefined : json['relativePath'] === null ? null : json['relativePath'],
        'deliveryStatus': json['deliveryStatus'],
        'issueCodes': json['issueCodes'],
        'recoverable': json['recoverable'],
    };
}

export function ArtifactInfoToJSON(json: any): ArtifactInfo {
    return ArtifactInfoToJSONTyped(json, false);
}

export function ArtifactInfoToJSONTyped(value?: ArtifactInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileId': value['fileId'],
        'fileSize': value['fileSize'],
        'fileName': value['fileName'],
        'mimeType': value['mimeType'],
        'relativePath': value['relativePath'],
        'deliveryStatus': value['deliveryStatus'],
        'issueCodes': value['issueCodes'],
        'recoverable': value['recoverable'],
    };
}

