/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AskUserQuestionOption 的公开协议结构。 / Public contract for ask user question option.
 * @export
 * @interface AskUserQuestionOption
 */
export interface AskUserQuestionOption {
    /**
     * 字段 text / text field。
     */
    text: string;
    /**
     * 字段 recommended / recommended field。
     */
    recommended: boolean;
}

/**
 * Check if a given object implements the AskUserQuestionOption interface.
 */
export function instanceOfAskUserQuestionOption(value: object): value is AskUserQuestionOption {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('recommended' in value) || value['recommended'] === undefined) return false;
    return true;
}

export function AskUserQuestionOptionFromJSON(json: any): AskUserQuestionOption {
    return AskUserQuestionOptionFromJSONTyped(json, false);
}

export function AskUserQuestionOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AskUserQuestionOption {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'recommended': json['recommended'],
    };
}

export function AskUserQuestionOptionToJSON(json: any): AskUserQuestionOption {
    return AskUserQuestionOptionToJSONTyped(json, false);
}

export function AskUserQuestionOptionToJSONTyped(value?: AskUserQuestionOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'recommended': value['recommended'],
    };
}

