/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AskUserQuestionExtensionContent 的公开协议结构。 / Public contract for ask user question extension content.
 * @export
 * @interface AskUserQuestionExtensionContent
 */
export interface AskUserQuestionExtensionContent {
    /**
     * 字段 selectedOptions / selected options field。
     */
    selectedOptions: Array<string>;
    /**
     * 字段 customInput / custom input field。
     */
    customInput?: string | null;
}

/**
 * Check if a given object implements the AskUserQuestionExtensionContent interface.
 */
export function instanceOfAskUserQuestionExtensionContent(value: object): value is AskUserQuestionExtensionContent {
    if (!('selectedOptions' in value) || value['selectedOptions'] === undefined) return false;
    return true;
}

export function AskUserQuestionExtensionContentFromJSON(json: any): AskUserQuestionExtensionContent {
    return AskUserQuestionExtensionContentFromJSONTyped(json, false);
}

export function AskUserQuestionExtensionContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): AskUserQuestionExtensionContent {
    if (json == null) {
        return json;
    }
    return {
        
        'selectedOptions': json['selectedOptions'],
        'customInput': json['customInput'] === undefined ? undefined : json['customInput'] === null ? null : json['customInput'],
    };
}

export function AskUserQuestionExtensionContentToJSON(json: any): AskUserQuestionExtensionContent {
    return AskUserQuestionExtensionContentToJSONTyped(json, false);
}

export function AskUserQuestionExtensionContentToJSONTyped(value?: AskUserQuestionExtensionContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'selectedOptions': value['selectedOptions'],
        'customInput': value['customInput'],
    };
}

