/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * AsyncTask 的公开协议结构。 / Public contract for async task.
 * @export
 * @interface AsyncTask
 */
export interface AsyncTask {
    /**
     * 异步任务 ID / asynchronous task ID。
     */
    taskId: string;
    /**
     * 字段 taskType / task type field。
     */
    taskType: string;
    /**
     * 标题 / title。
     */
    title: string;
    /**
     * 当前状态 / current status。
     */
    status: string;
    /**
     * 字段 progressPercent / progress percent field。
     */
    progressPercent?: number | null;
    /**
     * 字段 phase / phase field。
     */
    phase?: string | null;
    /**
     * 字段 statusMessage / status message field。
     */
    statusMessage?: string | null;
    /**
     * 字段 resultAvailable / result available field。
     */
    resultAvailable: boolean;
    /**
     * 字段 cancellable / cancellable field。
     */
    cancellable: boolean;
    /**
     * 字段 failureCode / failure code field。
     */
    failureCode?: string | null;
    /**
     * 字段 failureMessage / failure message field。
     */
    failureMessage?: string | null;
    /**
     * 字段 originConversationId / origin conversation id field。
     */
    originConversationId: string;
    /**
     * 字段 originMessageId / origin message id field。
     */
    originMessageId: string;
    /**
     * 字段 originToolId / origin tool id field。
     */
    originToolId: string;
    /**
     * 字段 originToolName / origin tool name field。
     */
    originToolName: string;
    /**
     * 字段 targetMessageId / target message id field。
     */
    targetMessageId: string;
    /**
     * 字段 notificationStatus / notification status field。
     */
    notificationStatus: string;
    /**
     * 字段 notificationMessageId / notification message id field。
     */
    notificationMessageId?: string | null;
    /**
     * 创建时间 / creation time。
     */
    createdTime: Date;
    /**
     * 字段 startedTime / started time field。
     */
    startedTime?: Date | null;
    /**
     * 字段 completedTime / completed time field。
     */
    completedTime?: Date | null;
    /**
     * 最后更新时间 / last update time。
     */
    lastUpdateTime: Date;
    /**
     * 字段 trackingStatus / tracking status field。
     */
    trackingStatus: string;
    /**
     * 字段 trackingFailureCode / tracking failure code field。
     */
    trackingFailureCode?: string | null;
    /**
     * 字段 lastPollError / last poll error field。
     */
    lastPollError?: string | null;
}

/**
 * Check if a given object implements the AsyncTask interface.
 */
export function instanceOfAsyncTask(value: object): value is AsyncTask {
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('taskType' in value) || value['taskType'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('resultAvailable' in value) || value['resultAvailable'] === undefined) return false;
    if (!('cancellable' in value) || value['cancellable'] === undefined) return false;
    if (!('originConversationId' in value) || value['originConversationId'] === undefined) return false;
    if (!('originMessageId' in value) || value['originMessageId'] === undefined) return false;
    if (!('originToolId' in value) || value['originToolId'] === undefined) return false;
    if (!('originToolName' in value) || value['originToolName'] === undefined) return false;
    if (!('targetMessageId' in value) || value['targetMessageId'] === undefined) return false;
    if (!('notificationStatus' in value) || value['notificationStatus'] === undefined) return false;
    if (!('createdTime' in value) || value['createdTime'] === undefined) return false;
    if (!('lastUpdateTime' in value) || value['lastUpdateTime'] === undefined) return false;
    if (!('trackingStatus' in value) || value['trackingStatus'] === undefined) return false;
    return true;
}

export function AsyncTaskFromJSON(json: any): AsyncTask {
    return AsyncTaskFromJSONTyped(json, false);
}

export function AsyncTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): AsyncTask {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'],
        'taskType': json['taskType'],
        'title': json['title'],
        'status': json['status'],
        'progressPercent': json['progressPercent'] === undefined ? undefined : json['progressPercent'] === null ? null : json['progressPercent'],
        'phase': json['phase'] === undefined ? undefined : json['phase'] === null ? null : json['phase'],
        'statusMessage': json['statusMessage'] === undefined ? undefined : json['statusMessage'] === null ? null : json['statusMessage'],
        'resultAvailable': json['resultAvailable'],
        'cancellable': json['cancellable'],
        'failureCode': json['failureCode'] === undefined ? undefined : json['failureCode'] === null ? null : json['failureCode'],
        'failureMessage': json['failureMessage'] === undefined ? undefined : json['failureMessage'] === null ? null : json['failureMessage'],
        'originConversationId': json['originConversationId'],
        'originMessageId': json['originMessageId'],
        'originToolId': json['originToolId'],
        'originToolName': json['originToolName'],
        'targetMessageId': json['targetMessageId'],
        'notificationStatus': json['notificationStatus'],
        'notificationMessageId': json['notificationMessageId'] === undefined ? undefined : json['notificationMessageId'] === null ? null : json['notificationMessageId'],
        'createdTime': (json['createdTime'] == null ? json['createdTime'] : parseDateTime(json['createdTime'])),
        'startedTime': json['startedTime'] === undefined ? undefined : json['startedTime'] === null ? null : (parseDateTime(json['startedTime'])),
        'completedTime': json['completedTime'] === undefined ? undefined : json['completedTime'] === null ? null : (parseDateTime(json['completedTime'])),
        'lastUpdateTime': (json['lastUpdateTime'] == null ? json['lastUpdateTime'] : parseDateTime(json['lastUpdateTime'])),
        'trackingStatus': json['trackingStatus'],
        'trackingFailureCode': json['trackingFailureCode'] === undefined ? undefined : json['trackingFailureCode'] === null ? null : json['trackingFailureCode'],
        'lastPollError': json['lastPollError'] === undefined ? undefined : json['lastPollError'] === null ? null : json['lastPollError'],
    };
}

export function AsyncTaskToJSON(json: any): AsyncTask {
    return AsyncTaskToJSONTyped(json, false);
}

export function AsyncTaskToJSONTyped(value?: AsyncTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskId': value['taskId'],
        'taskType': value['taskType'],
        'title': value['title'],
        'status': value['status'],
        'progressPercent': value['progressPercent'],
        'phase': value['phase'],
        'statusMessage': value['statusMessage'],
        'resultAvailable': value['resultAvailable'],
        'cancellable': value['cancellable'],
        'failureCode': value['failureCode'],
        'failureMessage': value['failureMessage'],
        'originConversationId': value['originConversationId'],
        'originMessageId': value['originMessageId'],
        'originToolId': value['originToolId'],
        'originToolName': value['originToolName'],
        'targetMessageId': value['targetMessageId'],
        'notificationStatus': value['notificationStatus'],
        'notificationMessageId': value['notificationMessageId'],
        'createdTime': value['createdTime'] == null ? value['createdTime'] : serializeDateTime(value['createdTime']),
        'startedTime': value['startedTime'] == null ? value['startedTime'] : serializeDateTime(value['startedTime']),
        'completedTime': value['completedTime'] == null ? value['completedTime'] : serializeDateTime(value['completedTime']),
        'lastUpdateTime': value['lastUpdateTime'] == null ? value['lastUpdateTime'] : serializeDateTime(value['lastUpdateTime']),
        'trackingStatus': value['trackingStatus'],
        'trackingFailureCode': value['trackingFailureCode'],
        'lastPollError': value['lastPollError'],
    };
}

