/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ChartNumberFormat 的公开协议结构。 / Public contract for chart number format.
 * @export
 * @interface ChartNumberFormat
 */
export interface ChartNumberFormat {
    /**
     * 类型判别值 / type discriminator。
     */
    type: string;
    /**
     * 字段 currency / currency field。
     */
    currency?: string | null;
    /**
     * 字段 decimalPlaces / decimal places field。
     */
    decimalPlaces: number;
    /**
     * 字段 valueScale / value scale field。
     */
    valueScale?: string | null;
}

/**
 * Check if a given object implements the ChartNumberFormat interface.
 */
export function instanceOfChartNumberFormat(value: object): value is ChartNumberFormat {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('decimalPlaces' in value) || value['decimalPlaces'] === undefined) return false;
    return true;
}

export function ChartNumberFormatFromJSON(json: any): ChartNumberFormat {
    return ChartNumberFormatFromJSONTyped(json, false);
}

export function ChartNumberFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChartNumberFormat {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'currency': json['currency'] === undefined ? undefined : json['currency'] === null ? null : json['currency'],
        'decimalPlaces': json['decimalPlaces'],
        'valueScale': json['valueScale'] === undefined ? undefined : json['valueScale'] === null ? null : json['valueScale'],
    };
}

export function ChartNumberFormatToJSON(json: any): ChartNumberFormat {
    return ChartNumberFormatToJSONTyped(json, false);
}

export function ChartNumberFormatToJSONTyped(value?: ChartNumberFormat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'currency': value['currency'],
        'decimalPlaces': value['decimalPlaces'],
        'valueScale': value['valueScale'],
    };
}

