/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ChartQualitySummary 的公开协议结构。 / Public contract for chart quality summary.
 * @export
 * @interface ChartQualitySummary
 */
export interface ChartQualitySummary {
    /**
     * 字段 nullValueCount / null value count field。
     */
    nullValueCount: number;
    /**
     * 字段 nullValueColumns / null value columns field。
     */
    nullValueColumns: Array<string>;
    /**
     * 字段 zeroFilledValueCount / zero filled value count field。
     */
    zeroFilledValueCount: number;
}

/**
 * Check if a given object implements the ChartQualitySummary interface.
 */
export function instanceOfChartQualitySummary(value: object): value is ChartQualitySummary {
    if (!('nullValueCount' in value) || value['nullValueCount'] === undefined) return false;
    if (!('nullValueColumns' in value) || value['nullValueColumns'] === undefined) return false;
    if (!('zeroFilledValueCount' in value) || value['zeroFilledValueCount'] === undefined) return false;
    return true;
}

export function ChartQualitySummaryFromJSON(json: any): ChartQualitySummary {
    return ChartQualitySummaryFromJSONTyped(json, false);
}

export function ChartQualitySummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChartQualitySummary {
    if (json == null) {
        return json;
    }
    return {
        
        'nullValueCount': json['nullValueCount'],
        'nullValueColumns': json['nullValueColumns'],
        'zeroFilledValueCount': json['zeroFilledValueCount'],
    };
}

export function ChartQualitySummaryToJSON(json: any): ChartQualitySummary {
    return ChartQualitySummaryToJSONTyped(json, false);
}

export function ChartQualitySummaryToJSONTyped(value?: ChartQualitySummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nullValueCount': value['nullValueCount'],
        'nullValueColumns': value['nullValueColumns'],
        'zeroFilledValueCount': value['zeroFilledValueCount'],
    };
}

