/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ChatModelConfig 的公开协议结构。 / Public contract for chat model config.
 * @export
 * @interface ChatModelConfig
 */
export interface ChatModelConfig {
    /**
     * 字段 maker / maker field。
     */
    maker: string;
    /**
     * 字段 modelName / model name field。
     */
    modelName: string;
    /**
     * 字段 modelLabel / model label field。
     */
    modelLabel: string;
    /**
     * 字段 modelDescription / model description field。
     */
    modelDescription: string;
    /**
     * 字段 maxContextTokens / max context tokens field。
     */
    maxContextTokens: number;
    /**
     * 字段 maxOutputTokens / max output tokens field。
     */
    maxOutputTokens: number;
    /**
     * 字段 supportImage / support image field。
     */
    supportImage: boolean;
    /**
     * 字段 supportVideo / support video field。
     */
    supportVideo: boolean;
    /**
     * 字段 thinkingMode / thinking mode field。
     */
    thinkingMode: boolean;
}

/**
 * Check if a given object implements the ChatModelConfig interface.
 */
export function instanceOfChatModelConfig(value: object): value is ChatModelConfig {
    if (!('maker' in value) || value['maker'] === undefined) return false;
    if (!('modelName' in value) || value['modelName'] === undefined) return false;
    if (!('modelLabel' in value) || value['modelLabel'] === undefined) return false;
    if (!('modelDescription' in value) || value['modelDescription'] === undefined) return false;
    if (!('maxContextTokens' in value) || value['maxContextTokens'] === undefined) return false;
    if (!('maxOutputTokens' in value) || value['maxOutputTokens'] === undefined) return false;
    if (!('supportImage' in value) || value['supportImage'] === undefined) return false;
    if (!('supportVideo' in value) || value['supportVideo'] === undefined) return false;
    if (!('thinkingMode' in value) || value['thinkingMode'] === undefined) return false;
    return true;
}

export function ChatModelConfigFromJSON(json: any): ChatModelConfig {
    return ChatModelConfigFromJSONTyped(json, false);
}

export function ChatModelConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatModelConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'maker': json['maker'],
        'modelName': json['modelName'],
        'modelLabel': json['modelLabel'],
        'modelDescription': json['modelDescription'],
        'maxContextTokens': json['maxContextTokens'],
        'maxOutputTokens': json['maxOutputTokens'],
        'supportImage': json['supportImage'],
        'supportVideo': json['supportVideo'],
        'thinkingMode': json['thinkingMode'],
    };
}

export function ChatModelConfigToJSON(json: any): ChatModelConfig {
    return ChatModelConfigToJSONTyped(json, false);
}

export function ChatModelConfigToJSONTyped(value?: ChatModelConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'maker': value['maker'],
        'modelName': value['modelName'],
        'modelLabel': value['modelLabel'],
        'modelDescription': value['modelDescription'],
        'maxContextTokens': value['maxContextTokens'],
        'maxOutputTokens': value['maxOutputTokens'],
        'supportImage': value['supportImage'],
        'supportVideo': value['supportVideo'],
        'thinkingMode': value['thinkingMode'],
    };
}

