/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { AssistantChatMessage } from './AssistantChatMessage';
import {
    instanceOfAssistantChatMessage,
    AssistantChatMessageFromJSON,
    AssistantChatMessageFromJSONTyped,
    AssistantChatMessageToJSON,
} from './AssistantChatMessage';
import type { SystemChatMessage } from './SystemChatMessage';
import {
    instanceOfSystemChatMessage,
    SystemChatMessageFromJSON,
    SystemChatMessageFromJSONTyped,
    SystemChatMessageToJSON,
} from './SystemChatMessage';
import type { ToolResponseChatMessage } from './ToolResponseChatMessage';
import {
    instanceOfToolResponseChatMessage,
    ToolResponseChatMessageFromJSON,
    ToolResponseChatMessageFromJSONTyped,
    ToolResponseChatMessageToJSON,
} from './ToolResponseChatMessage';
import type { UserChatMessage } from './UserChatMessage';
import {
    instanceOfUserChatMessage,
    UserChatMessageFromJSON,
    UserChatMessageFromJSONTyped,
    UserChatMessageToJSON,
} from './UserChatMessage';

/**
 * @type ChatMessage
 * ChatMessage 的公开协议结构。 / Public contract for chat message.
 * @export
 */
export type ChatMessage = { type: 'ASSISTANT' } & AssistantChatMessage | { type: 'SYSTEM' } & SystemChatMessage | { type: 'TOOL' } & ToolResponseChatMessage | { type: 'USER' } & UserChatMessage;

export function ChatMessageFromJSON(json: any): ChatMessage {
    return ChatMessageFromJSONTyped(json, false);
}

export function ChatMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessage {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'ASSISTANT':
            return Object.assign({}, AssistantChatMessageFromJSONTyped(json, true), { type: 'ASSISTANT' } as const);
        case 'SYSTEM':
            return Object.assign({}, SystemChatMessageFromJSONTyped(json, true), { type: 'SYSTEM' } as const);
        case 'TOOL':
            return Object.assign({}, ToolResponseChatMessageFromJSONTyped(json, true), { type: 'TOOL' } as const);
        case 'USER':
            return Object.assign({}, UserChatMessageFromJSONTyped(json, true), { type: 'USER' } as const);
        default:
            return json;
    }
}

export function ChatMessageToJSON(json: any): any {
    return ChatMessageToJSONTyped(json, false);
}

export function ChatMessageToJSONTyped(value?: ChatMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'ASSISTANT':
            return Object.assign({}, AssistantChatMessageToJSON(value), { 'type': 'ASSISTANT' } as const);
        case 'SYSTEM':
            return Object.assign({}, SystemChatMessageToJSON(value), { 'type': 'SYSTEM' } as const);
        case 'TOOL':
            return Object.assign({}, ToolResponseChatMessageToJSON(value), { 'type': 'TOOL' } as const);
        case 'USER':
            return Object.assign({}, UserChatMessageToJSON(value), { 'type': 'USER' } as const);
        default:
            return value;
    }
}

