/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ChatStreamProbeInput 的公开协议结构。 / Public contract for chat stream probe input.
 * @export
 * @interface ChatStreamProbeInput
 */
export interface ChatStreamProbeInput {
    /**
     * 字段 probeId / probe id field。
     */
    probeId: string;
}

/**
 * Check if a given object implements the ChatStreamProbeInput interface.
 */
export function instanceOfChatStreamProbeInput(value: object): value is ChatStreamProbeInput {
    if (!('probeId' in value) || value['probeId'] === undefined) return false;
    return true;
}

export function ChatStreamProbeInputFromJSON(json: any): ChatStreamProbeInput {
    return ChatStreamProbeInputFromJSONTyped(json, false);
}

export function ChatStreamProbeInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatStreamProbeInput {
    if (json == null) {
        return json;
    }
    return {
        
        'probeId': json['probeId'],
    };
}

export function ChatStreamProbeInputToJSON(json: any): ChatStreamProbeInput {
    return ChatStreamProbeInputToJSONTyped(json, false);
}

export function ChatStreamProbeInputToJSONTyped(value?: ChatStreamProbeInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'probeId': value['probeId'],
    };
}

