/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ChatOptions 的公开协议结构。 / Public contract for chat options.
 * @export
 * @interface ChatOptions
 */
export interface ChatOptions {
    /**
     * 字段 model / model field。
     */
    model?: string | null;
    /**
     * 字段 frequencyPenalty / frequency penalty field。
     */
    frequencyPenalty?: number | null;
    /**
     * 字段 maxTokens / max tokens field。
     */
    maxTokens?: number | null;
    /**
     * 字段 presencePenalty / presence penalty field。
     */
    presencePenalty?: number | null;
    /**
     * 字段 stopSequences / stop sequences field。
     */
    stopSequences?: Array<string> | null;
    /**
     * 字段 temperature / temperature field。
     */
    temperature?: number | null;
    /**
     * 字段 topP / top p field。
     */
    topP?: number | null;
}

/**
 * Check if a given object implements the ChatOptions interface.
 */
export function instanceOfChatOptions(value: object): value is ChatOptions {
    return true;
}

export function ChatOptionsFromJSON(json: any): ChatOptions {
    return ChatOptionsFromJSONTyped(json, false);
}

export function ChatOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'] === undefined ? undefined : json['model'] === null ? null : json['model'],
        'frequencyPenalty': json['frequencyPenalty'] === undefined ? undefined : json['frequencyPenalty'] === null ? null : json['frequencyPenalty'],
        'maxTokens': json['maxTokens'] === undefined ? undefined : json['maxTokens'] === null ? null : json['maxTokens'],
        'presencePenalty': json['presencePenalty'] === undefined ? undefined : json['presencePenalty'] === null ? null : json['presencePenalty'],
        'stopSequences': json['stopSequences'] === undefined ? undefined : json['stopSequences'] === null ? null : json['stopSequences'],
        'temperature': json['temperature'] === undefined ? undefined : json['temperature'] === null ? null : json['temperature'],
        'topP': json['topP'] === undefined ? undefined : json['topP'] === null ? null : json['topP'],
    };
}

export function ChatOptionsToJSON(json: any): ChatOptions {
    return ChatOptionsToJSONTyped(json, false);
}

export function ChatOptionsToJSONTyped(value?: ChatOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'frequencyPenalty': value['frequencyPenalty'],
        'maxTokens': value['maxTokens'],
        'presencePenalty': value['presencePenalty'],
        'stopSequences': value['stopSequences'],
        'temperature': value['temperature'],
        'topP': value['topP'],
    };
}

