/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ChatModelSpec 的公开协议结构。 / Public contract for chat model spec.
 * @export
 * @interface ChatModelSpec
 */
export interface ChatModelSpec {
    /**
     * 字段 keyGroupId / key group id field。
     */
    keyGroupId: number;
    /**
     * 字段 model / model field。
     */
    model: string;
    /**
     * 字段 thinking / thinking field。
     */
    thinking?: boolean | null;
    /**
     * 字段 stopSequences / stop sequences field。
     */
    stopSequences?: Array<string> | null;
    /**
     * 字段 temperature / temperature field。
     */
    temperature?: number | null;
    /**
     * 字段 maxTokens / max tokens field。
     */
    maxTokens?: number | null;
    /**
     * 字段 topP / top p field。
     */
    topP?: number | null;
    /**
     * 字段 topK / top k field。
     */
    topK?: number | null;
    /**
     * 字段 frequencyPenalty / frequency penalty field。
     */
    frequencyPenalty?: number | null;
    /**
     * 字段 presencePenalty / presence penalty field。
     */
    presencePenalty?: number | null;
}

/**
 * Check if a given object implements the ChatModelSpec interface.
 */
export function instanceOfChatModelSpec(value: object): value is ChatModelSpec {
    if (!('keyGroupId' in value) || value['keyGroupId'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function ChatModelSpecFromJSON(json: any): ChatModelSpec {
    return ChatModelSpecFromJSONTyped(json, false);
}

export function ChatModelSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatModelSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'keyGroupId': json['keyGroupId'],
        'model': json['model'],
        'thinking': json['thinking'] === undefined ? undefined : json['thinking'] === null ? null : json['thinking'],
        'stopSequences': json['stopSequences'] === undefined ? undefined : json['stopSequences'] === null ? null : json['stopSequences'],
        'temperature': json['temperature'] === undefined ? undefined : json['temperature'] === null ? null : json['temperature'],
        'maxTokens': json['maxTokens'] === undefined ? undefined : json['maxTokens'] === null ? null : json['maxTokens'],
        'topP': json['topP'] === undefined ? undefined : json['topP'] === null ? null : json['topP'],
        'topK': json['topK'] === undefined ? undefined : json['topK'] === null ? null : json['topK'],
        'frequencyPenalty': json['frequencyPenalty'] === undefined ? undefined : json['frequencyPenalty'] === null ? null : json['frequencyPenalty'],
        'presencePenalty': json['presencePenalty'] === undefined ? undefined : json['presencePenalty'] === null ? null : json['presencePenalty'],
    };
}

export function ChatModelSpecToJSON(json: any): ChatModelSpec {
    return ChatModelSpecToJSONTyped(json, false);
}

export function ChatModelSpecToJSONTyped(value?: ChatModelSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keyGroupId': value['keyGroupId'],
        'model': value['model'],
        'thinking': value['thinking'],
        'stopSequences': value['stopSequences'],
        'temperature': value['temperature'],
        'maxTokens': value['maxTokens'],
        'topP': value['topP'],
        'topK': value['topK'],
        'frequencyPenalty': value['frequencyPenalty'],
        'presencePenalty': value['presencePenalty'],
    };
}

