/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ChatModelConfig 的公开协议结构。 / Public contract for chat model config.
 * @export
 * @interface ChatModelConfig
 */
export interface ChatModelConfig {
    /**
     * 字段 maker / maker field。
     */
    maker: string;
    /**
     * 字段 modelName / model name field。
     */
    modelName: string;
    /**
     * 字段 modelLabel / model label field。
     */
    modelLabel: string;
    /**
     * 字段 modelDescription / model description field。
     */
    modelDescription: string;
    /**
     * 字段 maxContextTokens / max context tokens field。
     */
    maxContextTokens: number;
    /**
     * 字段 maxOutputTokens / max output tokens field。
     */
    maxOutputTokens: number;
    /**
     * 字段 supportImage / support image field。
     */
    supportImage: boolean;
    /**
     * 字段 supportVideo / support video field。
     */
    supportVideo: boolean;
    /**
     * 字段 thinkingMode / thinking mode field。
     */
    thinkingMode: boolean;
}

/**
 * Check if a given object implements the ChatModelConfig interface.
 */
export function instanceOfChatModelConfig(value: object): value is ChatModelConfig {
    if (!('maker' in value) || value['maker'] === undefined) return false;
    if (!('modelName' in value) || value['modelName'] === undefined) return false;
    if (!('modelLabel' in value) || value['modelLabel'] === undefined) return false;
    if (!('modelDescription' in value) || value['modelDescription'] === undefined) return false;
    if (!('maxContextTokens' in value) || value['maxContextTokens'] === undefined) return false;
    if (!('maxOutputTokens' in value) || value['maxOutputTokens'] === undefined) return false;
    if (!('supportImage' in value) || value['supportImage'] === undefined) return false;
    if (!('supportVideo' in value) || value['supportVideo'] === undefined) return false;
    if (!('thinkingMode' in value) || value['thinkingMode'] === undefined) return false;
    return true;
}

export function ChatModelConfigFromJSON(json: any): ChatModelConfig {
    return ChatModelConfigFromJSONTyped(json, false);
}

export function ChatModelConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatModelConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'maker': json['maker'],
        'modelName': json['modelName'],
        'modelLabel': json['modelLabel'],
        'modelDescription': json['modelDescription'],
        'maxContextTokens': json['maxContextTokens'],
        'maxOutputTokens': json['maxOutputTokens'],
        'supportImage': json['supportImage'],
        'supportVideo': json['supportVideo'],
        'thinkingMode': json['thinkingMode'],
    };
}

export function ChatModelConfigToJSON(json: any): ChatModelConfig {
    return ChatModelConfigToJSONTyped(json, false);
}

export function ChatModelConfigToJSONTyped(value?: ChatModelConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'maker': value['maker'],
        'modelName': value['modelName'],
        'modelLabel': value['modelLabel'],
        'modelDescription': value['modelDescription'],
        'maxContextTokens': value['maxContextTokens'],
        'maxOutputTokens': value['maxOutputTokens'],
        'supportImage': value['supportImage'],
        'supportVideo': value['supportVideo'],
        'thinkingMode': value['thinkingMode'],
    };
}

