/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ConfirmUploadInput 的公开协议结构。 / Public contract for confirm upload input.
 * @export
 * @interface ConfirmUploadInput
 */
export interface ConfirmUploadInput {
    /**
     * 字段 fileUk / file uk field。
     */
    fileUk: string;
    /**
     * 字段 contentMd5 / content md5 field。
     */
    contentMd5: string;
}

/**
 * Check if a given object implements the ConfirmUploadInput interface.
 */
export function instanceOfConfirmUploadInput(value: object): value is ConfirmUploadInput {
    if (!('fileUk' in value) || value['fileUk'] === undefined) return false;
    if (!('contentMd5' in value) || value['contentMd5'] === undefined) return false;
    return true;
}

export function ConfirmUploadInputFromJSON(json: any): ConfirmUploadInput {
    return ConfirmUploadInputFromJSONTyped(json, false);
}

export function ConfirmUploadInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmUploadInput {
    if (json == null) {
        return json;
    }
    return {
        
        'fileUk': json['fileUk'],
        'contentMd5': json['contentMd5'],
    };
}

export function ConfirmUploadInputToJSON(json: any): ConfirmUploadInput {
    return ConfirmUploadInputToJSONTyped(json, false);
}

export function ConfirmUploadInputToJSONTyped(value?: ConfirmUploadInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileUk': value['fileUk'],
        'contentMd5': value['contentMd5'],
    };
}

