/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ConversationShareRevoked 的公开协议结构。 / Public contract for conversation share revoked.
 * @export
 * @interface ConversationShareRevoked
 */
export interface ConversationShareRevoked {
    /**
     * 字段 shareId / share id field。
     */
    shareId: number;
}

/**
 * Check if a given object implements the ConversationShareRevoked interface.
 */
export function instanceOfConversationShareRevoked(value: object): value is ConversationShareRevoked {
    if (!('shareId' in value) || value['shareId'] === undefined) return false;
    return true;
}

export function ConversationShareRevokedFromJSON(json: any): ConversationShareRevoked {
    return ConversationShareRevokedFromJSONTyped(json, false);
}

export function ConversationShareRevokedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationShareRevoked {
    if (json == null) {
        return json;
    }
    return {
        
        'shareId': json['shareId'],
    };
}

export function ConversationShareRevokedToJSON(json: any): ConversationShareRevoked {
    return ConversationShareRevokedToJSONTyped(json, false);
}

export function ConversationShareRevokedToJSONTyped(value?: ConversationShareRevoked | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shareId': value['shareId'],
    };
}

