/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * ConversationShareRecord 的公开协议结构。 / Public contract for conversation share record.
 * @export
 * @interface ConversationShareRecord
 */
export interface ConversationShareRecord {
    /**
     * 字段 shareId / share id field。
     */
    shareId: number;
    /**
     * 字段 shareCode / share code field。
     */
    shareCode: string;
    /**
     * 字段 serverName / server name field。
     */
    serverName: string;
    /**
     * 字段 accessMode / access mode field。
     */
    accessMode: string;
    /**
     * 当前状态 / current status。
     */
    status: string;
    /**
     * 字段 expiresAt / expires at field。
     */
    expiresAt?: Date | null;
    /**
     * 创建时间 / creation time。
     */
    createdTime: Date;
    /**
     * 最后更新时间 / last update time。
     */
    lastUpdateTime: Date;
}

/**
 * Check if a given object implements the ConversationShareRecord interface.
 */
export function instanceOfConversationShareRecord(value: object): value is ConversationShareRecord {
    if (!('shareId' in value) || value['shareId'] === undefined) return false;
    if (!('shareCode' in value) || value['shareCode'] === undefined) return false;
    if (!('serverName' in value) || value['serverName'] === undefined) return false;
    if (!('accessMode' in value) || value['accessMode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdTime' in value) || value['createdTime'] === undefined) return false;
    if (!('lastUpdateTime' in value) || value['lastUpdateTime'] === undefined) return false;
    return true;
}

export function ConversationShareRecordFromJSON(json: any): ConversationShareRecord {
    return ConversationShareRecordFromJSONTyped(json, false);
}

export function ConversationShareRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationShareRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'shareId': json['shareId'],
        'shareCode': json['shareCode'],
        'serverName': json['serverName'],
        'accessMode': json['accessMode'],
        'status': json['status'],
        'expiresAt': json['expiresAt'] === undefined ? undefined : json['expiresAt'] === null ? null : (parseDateTime(json['expiresAt'])),
        'createdTime': (json['createdTime'] == null ? json['createdTime'] : parseDateTime(json['createdTime'])),
        'lastUpdateTime': (json['lastUpdateTime'] == null ? json['lastUpdateTime'] : parseDateTime(json['lastUpdateTime'])),
    };
}

export function ConversationShareRecordToJSON(json: any): ConversationShareRecord {
    return ConversationShareRecordToJSONTyped(json, false);
}

export function ConversationShareRecordToJSONTyped(value?: ConversationShareRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shareId': value['shareId'],
        'shareCode': value['shareCode'],
        'serverName': value['serverName'],
        'accessMode': value['accessMode'],
        'status': value['status'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
        'createdTime': value['createdTime'] == null ? value['createdTime'] : serializeDateTime(value['createdTime']),
        'lastUpdateTime': value['lastUpdateTime'] == null ? value['lastUpdateTime'] : serializeDateTime(value['lastUpdateTime']),
    };
}

