/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * ConversationReadReceipt 的公开协议结构。 / Public contract for conversation read receipt.
 * @export
 * @interface ConversationReadReceipt
 */
export interface ConversationReadReceipt {
    /**
     * 会话 ID / conversation ID。
     */
    conversationId: string;
    /**
     * 字段 executionStatus / execution status field。
     */
    executionStatus: string;
    /**
     * 字段 activeMessageId / active message id field。
     */
    activeMessageId?: string | null;
    /**
     * 字段 executionEpoch / execution epoch field。
     */
    executionEpoch?: string | null;
    /**
     * 字段 executionStartedTime / execution started time field。
     */
    executionStartedTime?: Date | null;
    /**
     * 字段 latestTerminalMessageId / latest terminal message id field。
     */
    latestTerminalMessageId?: string | null;
    /**
     * 字段 latestTerminalTime / latest terminal time field。
     */
    latestTerminalTime?: Date | null;
    /**
     * 字段 hasUnreadCompletion / has unread completion field。
     */
    hasUnreadCompletion: boolean;
}

/**
 * Check if a given object implements the ConversationReadReceipt interface.
 */
export function instanceOfConversationReadReceipt(value: object): value is ConversationReadReceipt {
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('executionStatus' in value) || value['executionStatus'] === undefined) return false;
    if (!('hasUnreadCompletion' in value) || value['hasUnreadCompletion'] === undefined) return false;
    return true;
}

export function ConversationReadReceiptFromJSON(json: any): ConversationReadReceipt {
    return ConversationReadReceiptFromJSONTyped(json, false);
}

export function ConversationReadReceiptFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationReadReceipt {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationId': json['conversationId'],
        'executionStatus': json['executionStatus'],
        'activeMessageId': json['activeMessageId'] === undefined ? undefined : json['activeMessageId'] === null ? null : json['activeMessageId'],
        'executionEpoch': json['executionEpoch'] === undefined ? undefined : json['executionEpoch'] === null ? null : json['executionEpoch'],
        'executionStartedTime': json['executionStartedTime'] === undefined ? undefined : json['executionStartedTime'] === null ? null : (parseDateTime(json['executionStartedTime'])),
        'latestTerminalMessageId': json['latestTerminalMessageId'] === undefined ? undefined : json['latestTerminalMessageId'] === null ? null : json['latestTerminalMessageId'],
        'latestTerminalTime': json['latestTerminalTime'] === undefined ? undefined : json['latestTerminalTime'] === null ? null : (parseDateTime(json['latestTerminalTime'])),
        'hasUnreadCompletion': json['hasUnreadCompletion'],
    };
}

export function ConversationReadReceiptToJSON(json: any): ConversationReadReceipt {
    return ConversationReadReceiptToJSONTyped(json, false);
}

export function ConversationReadReceiptToJSONTyped(value?: ConversationReadReceipt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversationId': value['conversationId'],
        'executionStatus': value['executionStatus'],
        'activeMessageId': value['activeMessageId'],
        'executionEpoch': value['executionEpoch'],
        'executionStartedTime': value['executionStartedTime'] == null ? value['executionStartedTime'] : serializeDateTime(value['executionStartedTime']),
        'latestTerminalMessageId': value['latestTerminalMessageId'],
        'latestTerminalTime': value['latestTerminalTime'] == null ? value['latestTerminalTime'] : serializeDateTime(value['latestTerminalTime']),
        'hasUnreadCompletion': value['hasUnreadCompletion'],
    };
}

