/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConversationShareRecord } from './ConversationShareRecord';
import {
    ConversationShareRecordFromJSON,
    ConversationShareRecordFromJSONTyped,
    ConversationShareRecordToJSON,
    ConversationShareRecordToJSONTyped,
} from './ConversationShareRecord';

/**
 * ConversationShareList 的公开协议结构。 / Public contract for conversation share list.
 * @export
 * @interface ConversationShareList
 */
export interface ConversationShareList {
    /**
     * 记录列表 / records。
     */
    records: Array<ConversationShareRecord>;
}

/**
 * Check if a given object implements the ConversationShareList interface.
 */
export function instanceOfConversationShareList(value: object): value is ConversationShareList {
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function ConversationShareListFromJSON(json: any): ConversationShareList {
    return ConversationShareListFromJSONTyped(json, false);
}

export function ConversationShareListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationShareList {
    if (json == null) {
        return json;
    }
    return {
        
        'records': ((json['records'] as Array<any>).map(ConversationShareRecordFromJSON)),
    };
}

export function ConversationShareListToJSON(json: any): ConversationShareList {
    return ConversationShareListToJSONTyped(json, false);
}

export function ConversationShareListToJSONTyped(value?: ConversationShareList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'records': ((value['records'] as Array<any>).map(ConversationShareRecordToJSON)),
    };
}

