/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageInfo } from './PageInfo';
import {
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
    PageInfoToJSONTyped,
} from './PageInfo';
import type { ConversationMessage } from './ConversationMessage';
import {
    ConversationMessageFromJSON,
    ConversationMessageFromJSONTyped,
    ConversationMessageToJSON,
    ConversationMessageToJSONTyped,
} from './ConversationMessage';

/**
 * ConversationMessagePage 的公开协议结构。 / Public contract for conversation message page.
 * @export
 * @interface ConversationMessagePage
 */
export interface ConversationMessagePage {
    /**
     * 记录列表 / records。
     */
    records: Array<ConversationMessage>;
    /**
     * 分页信息 / page metadata。
     */
    page: PageInfo;
}

/**
 * Check if a given object implements the ConversationMessagePage interface.
 */
export function instanceOfConversationMessagePage(value: object): value is ConversationMessagePage {
    if (!('records' in value) || value['records'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    return true;
}

export function ConversationMessagePageFromJSON(json: any): ConversationMessagePage {
    return ConversationMessagePageFromJSONTyped(json, false);
}

export function ConversationMessagePageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationMessagePage {
    if (json == null) {
        return json;
    }
    return {
        
        'records': ((json['records'] as Array<any>).map(ConversationMessageFromJSON)),
        'page': PageInfoFromJSON(json['page']),
    };
}

export function ConversationMessagePageToJSON(json: any): ConversationMessagePage {
    return ConversationMessagePageToJSONTyped(json, false);
}

export function ConversationMessagePageToJSONTyped(value?: ConversationMessagePage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'records': ((value['records'] as Array<any>).map(ConversationMessageToJSON)),
        'page': PageInfoToJSON(value['page']),
    };
}

