/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ConversationStats 的公开协议结构。 / Public contract for conversation stats.
 * @export
 * @interface ConversationStats
 */
export interface ConversationStats {
    /**
     * 字段 publishId / publish id field。
     */
    publishId: string;
    /**
     * 字段 totalConversations / total conversations field。
     */
    totalConversations: number;
    /**
     * 字段 activeConversations / active conversations field。
     */
    activeConversations: number;
    /**
     * 字段 totalMessages / total messages field。
     */
    totalMessages: number;
    /**
     * 总 Token 数 / total token count。
     */
    totalTokens: number;
    /**
     * 字段 avgMessagesPerConversation / avg messages per conversation field。
     */
    avgMessagesPerConversation: number;
}

/**
 * Check if a given object implements the ConversationStats interface.
 */
export function instanceOfConversationStats(value: object): value is ConversationStats {
    if (!('publishId' in value) || value['publishId'] === undefined) return false;
    if (!('totalConversations' in value) || value['totalConversations'] === undefined) return false;
    if (!('activeConversations' in value) || value['activeConversations'] === undefined) return false;
    if (!('totalMessages' in value) || value['totalMessages'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    if (!('avgMessagesPerConversation' in value) || value['avgMessagesPerConversation'] === undefined) return false;
    return true;
}

export function ConversationStatsFromJSON(json: any): ConversationStats {
    return ConversationStatsFromJSONTyped(json, false);
}

export function ConversationStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationStats {
    if (json == null) {
        return json;
    }
    return {
        
        'publishId': json['publishId'],
        'totalConversations': json['totalConversations'],
        'activeConversations': json['activeConversations'],
        'totalMessages': json['totalMessages'],
        'totalTokens': json['totalTokens'],
        'avgMessagesPerConversation': json['avgMessagesPerConversation'],
    };
}

export function ConversationStatsToJSON(json: any): ConversationStats {
    return ConversationStatsToJSONTyped(json, false);
}

export function ConversationStatsToJSONTyped(value?: ConversationStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'publishId': value['publishId'],
        'totalConversations': value['totalConversations'],
        'activeConversations': value['activeConversations'],
        'totalMessages': value['totalMessages'],
        'totalTokens': value['totalTokens'],
        'avgMessagesPerConversation': value['avgMessagesPerConversation'],
    };
}

