/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * CreateFileInput 的公开协议结构。 / Public contract for create file input.
 * @export
 * @interface CreateFileInput
 */
export interface CreateFileInput {
    /**
     * 文件名 / file name。
     */
    fileName: string;
    /**
     * 字段 contentMd5 / content md5 field。
     */
    contentMd5: string;
}

/**
 * Check if a given object implements the CreateFileInput interface.
 */
export function instanceOfCreateFileInput(value: object): value is CreateFileInput {
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('contentMd5' in value) || value['contentMd5'] === undefined) return false;
    return true;
}

export function CreateFileInputFromJSON(json: any): CreateFileInput {
    return CreateFileInputFromJSONTyped(json, false);
}

export function CreateFileInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFileInput {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['fileName'],
        'contentMd5': json['contentMd5'],
    };
}

export function CreateFileInputToJSON(json: any): CreateFileInput {
    return CreateFileInputToJSONTyped(json, false);
}

export function CreateFileInputToJSONTyped(value?: CreateFileInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileName': value['fileName'],
        'contentMd5': value['contentMd5'],
    };
}

