/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * FileExists 的公开协议结构。 / Public contract for file exists.
 * @export
 * @interface FileExists
 */
export interface FileExists {
    /**
     * 字段 exists / exists field。
     */
    _exists: boolean;
}

/**
 * Check if a given object implements the FileExists interface.
 */
export function instanceOfFileExists(value: object): value is FileExists {
    if ((!('_exists' in (value as Record<string, any>)) && !('exists' in (value as Record<string, any>))) || ((value as Record<string, any>)['_exists'] === undefined && (value as Record<string, any>)['exists'] === undefined)) return false;
    return true;
}

export function FileExistsFromJSON(json: any): FileExists {
    return FileExistsFromJSONTyped(json, false);
}

export function FileExistsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileExists {
    if (json == null) {
        return json;
    }
    return {
        
        '_exists': json['exists'],
    };
}

export function FileExistsToJSON(json: any): FileExists {
    return FileExistsToJSONTyped(json, false);
}

export function FileExistsToJSONTyped(value?: FileExists | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exists': value['_exists'],
    };
}

