/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * InstantChartColumn 的公开协议结构。 / Public contract for instant chart column.
 * @export
 * @interface InstantChartColumn
 */
export interface InstantChartColumn {
    /**
     * 字段 name / name field。
     */
    name: string;
    /**
     * 类型判别值 / type discriminator。
     */
    type: InstantChartColumnTypeEnum;
    /**
     * 字段 values / values field。
     */
    values: Array<Date | null>;
}


/**
 * @export
 */
export const InstantChartColumnTypeEnum = {
    Instant: 'INSTANT',
} as const;
export type InstantChartColumnTypeEnum = typeof InstantChartColumnTypeEnum[keyof typeof InstantChartColumnTypeEnum];


/**
 * Check if a given object implements the InstantChartColumn interface.
 */
export function instanceOfInstantChartColumn(value: object): value is InstantChartColumn {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'INSTANT') return false;
    
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function InstantChartColumnFromJSON(json: any): InstantChartColumn {
    return InstantChartColumnFromJSONTyped(json, false);
}

export function InstantChartColumnFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstantChartColumn {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'values': json['values'],
    };
}

export function InstantChartColumnToJSON(json: any): InstantChartColumn {
    return InstantChartColumnToJSONTyped(json, false);
}

export function InstantChartColumnToJSONTyped(value?: InstantChartColumn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'values': value['values'],
    };
}

