/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JsRunScriptExtensionContent } from './JsRunScriptExtensionContent';
import {
    JsRunScriptExtensionContentFromJSON,
    JsRunScriptExtensionContentFromJSONTyped,
    JsRunScriptExtensionContentToJSON,
    JsRunScriptExtensionContentToJSONTyped,
} from './JsRunScriptExtensionContent';

/**
 * JsRunScriptExtensionToolExtension 的公开协议结构。 / Public contract for js run script extension tool extension.
 * @export
 * @interface JsRunScriptExtensionToolExtension
 */
export interface JsRunScriptExtensionToolExtension {
    /**
     * 扩展类别判别值 / extension category discriminator。
     */
    category: JsRunScriptExtensionToolExtensionCategoryEnum;
    /**
     * 与类别对应的强类型内容 / strongly typed content for the category。
     */
    content: JsRunScriptExtensionContent;
    /**
     * 是否使用独立视图渲染 / whether to use a dedicated view。
     */
    specialRender: boolean;
}


/**
 * @export
 */
export const JsRunScriptExtensionToolExtensionCategoryEnum = {
    JsRunScript: 'jsRunScript',
} as const;
export type JsRunScriptExtensionToolExtensionCategoryEnum = typeof JsRunScriptExtensionToolExtensionCategoryEnum[keyof typeof JsRunScriptExtensionToolExtensionCategoryEnum];


/**
 * Check if a given object implements the JsRunScriptExtensionToolExtension interface.
 */
export function instanceOfJsRunScriptExtensionToolExtension(value: object): value is JsRunScriptExtensionToolExtension {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (value['category'] !== 'jsRunScript') return false;
    
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('specialRender' in value) || value['specialRender'] === undefined) return false;
    return true;
}

export function JsRunScriptExtensionToolExtensionFromJSON(json: any): JsRunScriptExtensionToolExtension {
    return JsRunScriptExtensionToolExtensionFromJSONTyped(json, false);
}

export function JsRunScriptExtensionToolExtensionFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsRunScriptExtensionToolExtension {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'],
        'content': JsRunScriptExtensionContentFromJSON(json['content']),
        'specialRender': json['specialRender'],
    };
}

export function JsRunScriptExtensionToolExtensionToJSON(json: any): JsRunScriptExtensionToolExtension {
    return JsRunScriptExtensionToolExtensionToJSONTyped(json, false);
}

export function JsRunScriptExtensionToolExtensionToJSONTyped(value?: JsRunScriptExtensionToolExtension | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'content': JsRunScriptExtensionContentToJSON(value['content']),
        'specialRender': value['specialRender'],
    };
}

