/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * LocalTimeChartColumn 的公开协议结构。 / Public contract for local time chart column.
 * @export
 * @interface LocalTimeChartColumn
 */
export interface LocalTimeChartColumn {
    /**
     * 字段 name / name field。
     */
    name: string;
    /**
     * 类型判别值 / type discriminator。
     */
    type: LocalTimeChartColumnTypeEnum;
    /**
     * 字段 values / values field。
     */
    values: Array<string | null>;
}


/**
 * @export
 */
export const LocalTimeChartColumnTypeEnum = {
    LocalTime: 'LOCAL_TIME',
} as const;
export type LocalTimeChartColumnTypeEnum = typeof LocalTimeChartColumnTypeEnum[keyof typeof LocalTimeChartColumnTypeEnum];


/**
 * Check if a given object implements the LocalTimeChartColumn interface.
 */
export function instanceOfLocalTimeChartColumn(value: object): value is LocalTimeChartColumn {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'LOCAL_TIME') return false;
    
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function LocalTimeChartColumnFromJSON(json: any): LocalTimeChartColumn {
    return LocalTimeChartColumnFromJSONTyped(json, false);
}

export function LocalTimeChartColumnFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalTimeChartColumn {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'values': json['values'],
    };
}

export function LocalTimeChartColumnToJSON(json: any): LocalTimeChartColumn {
    return LocalTimeChartColumnToJSONTyped(json, false);
}

export function LocalTimeChartColumnToJSONTyped(value?: LocalTimeChartColumn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'values': value['values'],
    };
}

