/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * LocalDateChartColumn 的公开协议结构。 / Public contract for local date chart column.
 * @export
 * @interface LocalDateChartColumn
 */
export interface LocalDateChartColumn {
    /**
     * 字段 name / name field。
     */
    name: string;
    /**
     * 类型判别值 / type discriminator。
     */
    type: LocalDateChartColumnTypeEnum;
    /**
     * 字段 values / values field。
     */
    values: Array<Date | null>;
}


/**
 * @export
 */
export const LocalDateChartColumnTypeEnum = {
    LocalDate: 'LOCAL_DATE',
} as const;
export type LocalDateChartColumnTypeEnum = typeof LocalDateChartColumnTypeEnum[keyof typeof LocalDateChartColumnTypeEnum];


/**
 * Check if a given object implements the LocalDateChartColumn interface.
 */
export function instanceOfLocalDateChartColumn(value: object): value is LocalDateChartColumn {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'LOCAL_DATE') return false;
    
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function LocalDateChartColumnFromJSON(json: any): LocalDateChartColumn {
    return LocalDateChartColumnFromJSONTyped(json, false);
}

export function LocalDateChartColumnFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalDateChartColumn {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'values': json['values'],
    };
}

export function LocalDateChartColumnToJSON(json: any): LocalDateChartColumn {
    return LocalDateChartColumnToJSONTyped(json, false);
}

export function LocalDateChartColumnToJSONTyped(value?: LocalDateChartColumn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'values': value['values'],
    };
}

