/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VariableBinding } from './VariableBinding';
import {
    VariableBindingFromJSON,
    VariableBindingFromJSONTyped,
    VariableBindingToJSON,
    VariableBindingToJSONTyped,
} from './VariableBinding';

/**
 * MathFormulaExtensionContent 的公开协议结构。 / Public contract for math formula extension content.
 * @export
 * @interface MathFormulaExtensionContent
 */
export interface MathFormulaExtensionContent {
    /**
     * 字段 expression / expression field。
     */
    expression: string;
    /**
     * 字段 variables / variables field。
     */
    variables?: Array<VariableBinding> | null;
}

/**
 * Check if a given object implements the MathFormulaExtensionContent interface.
 */
export function instanceOfMathFormulaExtensionContent(value: object): value is MathFormulaExtensionContent {
    if (!('expression' in value) || value['expression'] === undefined) return false;
    return true;
}

export function MathFormulaExtensionContentFromJSON(json: any): MathFormulaExtensionContent {
    return MathFormulaExtensionContentFromJSONTyped(json, false);
}

export function MathFormulaExtensionContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MathFormulaExtensionContent {
    if (json == null) {
        return json;
    }
    return {
        
        'expression': json['expression'],
        'variables': json['variables'] === undefined ? undefined : json['variables'] === null ? null : ((json['variables'] as Array<any>).map(VariableBindingFromJSON)),
    };
}

export function MathFormulaExtensionContentToJSON(json: any): MathFormulaExtensionContent {
    return MathFormulaExtensionContentToJSONTyped(json, false);
}

export function MathFormulaExtensionContentToJSONTyped(value?: MathFormulaExtensionContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expression': value['expression'],
        'variables': value['variables'] == null ? undefined : ((value['variables'] as Array<any>).map(VariableBindingToJSON)),
    };
}

