/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatModelConfig } from './ChatModelConfig';
import {
    ChatModelConfigFromJSON,
    ChatModelConfigFromJSONTyped,
    ChatModelConfigToJSON,
    ChatModelConfigToJSONTyped,
} from './ChatModelConfig';

/**
 * ModelKeyGroup 的公开协议结构。 / Public contract for model key group.
 * @export
 * @interface ModelKeyGroup
 */
export interface ModelKeyGroup {
    /**
     * 字段 keyGroupId / key group id field。
     */
    keyGroupId: number;
    /**
     * 字段 keyGroupName / key group name field。
     */
    keyGroupName: string;
    /**
     * 字段 models / models field。
     */
    models: Array<ChatModelConfig>;
}

/**
 * Check if a given object implements the ModelKeyGroup interface.
 */
export function instanceOfModelKeyGroup(value: object): value is ModelKeyGroup {
    if (!('keyGroupId' in value) || value['keyGroupId'] === undefined) return false;
    if (!('keyGroupName' in value) || value['keyGroupName'] === undefined) return false;
    if (!('models' in value) || value['models'] === undefined) return false;
    return true;
}

export function ModelKeyGroupFromJSON(json: any): ModelKeyGroup {
    return ModelKeyGroupFromJSONTyped(json, false);
}

export function ModelKeyGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelKeyGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'keyGroupId': json['keyGroupId'],
        'keyGroupName': json['keyGroupName'],
        'models': ((json['models'] as Array<any>).map(ChatModelConfigFromJSON)),
    };
}

export function ModelKeyGroupToJSON(json: any): ModelKeyGroup {
    return ModelKeyGroupToJSONTyped(json, false);
}

export function ModelKeyGroupToJSONTyped(value?: ModelKeyGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keyGroupId': value['keyGroupId'],
        'keyGroupName': value['keyGroupName'],
        'models': ((value['models'] as Array<any>).map(ChatModelConfigToJSON)),
    };
}

