/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * MultimodalMediaAttachment 的公开协议结构。 / Public contract for multimodal media attachment.
 * @export
 * @interface MultimodalMediaAttachment
 */
export interface MultimodalMediaAttachment {
    /**
     * 文件名 / file name。
     */
    fileName: string;
    /**
     * MIME 类型 / MIME type。
     */
    mimeType: string;
    /**
     * 字段 data / data field。
     */
    data: string;
}

/**
 * Check if a given object implements the MultimodalMediaAttachment interface.
 */
export function instanceOfMultimodalMediaAttachment(value: object): value is MultimodalMediaAttachment {
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function MultimodalMediaAttachmentFromJSON(json: any): MultimodalMediaAttachment {
    return MultimodalMediaAttachmentFromJSONTyped(json, false);
}

export function MultimodalMediaAttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultimodalMediaAttachment {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['fileName'],
        'mimeType': json['mimeType'],
        'data': json['data'],
    };
}

export function MultimodalMediaAttachmentToJSON(json: any): MultimodalMediaAttachment {
    return MultimodalMediaAttachmentToJSONTyped(json, false);
}

export function MultimodalMediaAttachmentToJSONTyped(value?: MultimodalMediaAttachment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileName': value['fileName'],
        'mimeType': value['mimeType'],
        'data': value['data'],
    };
}

