/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PageInfo 的公开协议结构。 / Public contract for page info.
 * @export
 * @interface PageInfo
 */
export interface PageInfo {
    /**
     * 字段 current / current field。
     */
    current: number;
    /**
     * 大小（字节）或分页容量 / byte size or page size。
     */
    size: number;
    /**
     * 字段 total / total field。
     */
    total: number;
}

/**
 * Check if a given object implements the PageInfo interface.
 */
export function instanceOfPageInfo(value: object): value is PageInfo {
    if (!('current' in value) || value['current'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function PageInfoFromJSON(json: any): PageInfo {
    return PageInfoFromJSONTyped(json, false);
}

export function PageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'current': json['current'],
        'size': json['size'],
        'total': json['total'],
    };
}

export function PageInfoToJSON(json: any): PageInfo {
    return PageInfoToJSONTyped(json, false);
}

export function PageInfoToJSONTyped(value?: PageInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current': value['current'],
        'size': value['size'],
        'total': value['total'],
    };
}

