/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PlanApprovalInput 的公开协议结构。 / Public contract for plan approval input.
 * @export
 * @interface PlanApprovalInput
 */
export interface PlanApprovalInput {
    /**
     * 会话 ID / conversation ID。
     */
    conversationId: string;
    /**
     * 消息 ID / message ID。
     */
    messageId: string;
    /**
     * 字段 approved / approved field。
     */
    approved: boolean;
    /**
     * 字段 feedback / feedback field。
     */
    feedback?: string | null;
}

/**
 * Check if a given object implements the PlanApprovalInput interface.
 */
export function instanceOfPlanApprovalInput(value: object): value is PlanApprovalInput {
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('approved' in value) || value['approved'] === undefined) return false;
    return true;
}

export function PlanApprovalInputFromJSON(json: any): PlanApprovalInput {
    return PlanApprovalInputFromJSONTyped(json, false);
}

export function PlanApprovalInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanApprovalInput {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationId': json['conversationId'],
        'messageId': json['messageId'],
        'approved': json['approved'],
        'feedback': json['feedback'] === undefined ? undefined : json['feedback'] === null ? null : json['feedback'],
    };
}

export function PlanApprovalInputToJSON(json: any): PlanApprovalInput {
    return PlanApprovalInputToJSONTyped(json, false);
}

export function PlanApprovalInputToJSONTyped(value?: PlanApprovalInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversationId': value['conversationId'],
        'messageId': value['messageId'],
        'approved': value['approved'],
        'feedback': value['feedback'],
    };
}

