/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * SkillResourceExtensionContent 的公开协议结构。 / Public contract for skill resource extension content.
 * @export
 * @interface SkillResourceExtensionContent
 */
export interface SkillResourceExtensionContent {
    /**
     * 字段 operationType / operation type field。
     */
    operationType: string;
    /**
     * 字段 filepath / filepath field。
     */
    filepath: string;
}

/**
 * Check if a given object implements the SkillResourceExtensionContent interface.
 */
export function instanceOfSkillResourceExtensionContent(value: object): value is SkillResourceExtensionContent {
    if (!('operationType' in value) || value['operationType'] === undefined) return false;
    if (!('filepath' in value) || value['filepath'] === undefined) return false;
    return true;
}

export function SkillResourceExtensionContentFromJSON(json: any): SkillResourceExtensionContent {
    return SkillResourceExtensionContentFromJSONTyped(json, false);
}

export function SkillResourceExtensionContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillResourceExtensionContent {
    if (json == null) {
        return json;
    }
    return {
        
        'operationType': json['operationType'],
        'filepath': json['filepath'],
    };
}

export function SkillResourceExtensionContentToJSON(json: any): SkillResourceExtensionContent {
    return SkillResourceExtensionContentToJSONTyped(json, false);
}

export function SkillResourceExtensionContentToJSONTyped(value?: SkillResourceExtensionContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operationType': value['operationType'],
        'filepath': value['filepath'],
    };
}

