/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SqlResultColumnSchema } from './SqlResultColumnSchema';
import {
    SqlResultColumnSchemaFromJSON,
    SqlResultColumnSchemaFromJSONTyped,
    SqlResultColumnSchemaToJSON,
    SqlResultColumnSchemaToJSONTyped,
} from './SqlResultColumnSchema';

/**
 * SqlQueryResultExtensionContent 的公开协议结构。 / Public contract for sql query result extension content.
 * @export
 * @interface SqlQueryResultExtensionContent
 */
export interface SqlQueryResultExtensionContent {
    /**
     * 字段 resultId / result id field。
     */
    resultId: string;
    /**
     * 字段 rowCount / row count field。
     */
    rowCount: number;
    /**
     * 字段 totalRowCount / total row count field。
     */
    totalRowCount: number;
    /**
     * 字段 columnCount / column count field。
     */
    columnCount: number;
    /**
     * 字段 columns / columns field。
     */
    columns: Array<string>;
    /**
     * 字段 schema / schema field。
     */
    schema: Array<SqlResultColumnSchema>;
    /**
     * 字段 truncated / truncated field。
     */
    truncated: boolean;
    /**
     * 字段 limit / limit field。
     */
    limit: number;
}

/**
 * Check if a given object implements the SqlQueryResultExtensionContent interface.
 */
export function instanceOfSqlQueryResultExtensionContent(value: object): value is SqlQueryResultExtensionContent {
    if (!('resultId' in value) || value['resultId'] === undefined) return false;
    if (!('rowCount' in value) || value['rowCount'] === undefined) return false;
    if (!('totalRowCount' in value) || value['totalRowCount'] === undefined) return false;
    if (!('columnCount' in value) || value['columnCount'] === undefined) return false;
    if (!('columns' in value) || value['columns'] === undefined) return false;
    if (!('schema' in value) || value['schema'] === undefined) return false;
    if (!('truncated' in value) || value['truncated'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function SqlQueryResultExtensionContentFromJSON(json: any): SqlQueryResultExtensionContent {
    return SqlQueryResultExtensionContentFromJSONTyped(json, false);
}

export function SqlQueryResultExtensionContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SqlQueryResultExtensionContent {
    if (json == null) {
        return json;
    }
    return {
        
        'resultId': json['resultId'],
        'rowCount': json['rowCount'],
        'totalRowCount': json['totalRowCount'],
        'columnCount': json['columnCount'],
        'columns': json['columns'],
        'schema': ((json['schema'] as Array<any>).map(SqlResultColumnSchemaFromJSON)),
        'truncated': json['truncated'],
        'limit': json['limit'],
    };
}

export function SqlQueryResultExtensionContentToJSON(json: any): SqlQueryResultExtensionContent {
    return SqlQueryResultExtensionContentToJSONTyped(json, false);
}

export function SqlQueryResultExtensionContentToJSONTyped(value?: SqlQueryResultExtensionContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resultId': value['resultId'],
        'rowCount': value['rowCount'],
        'totalRowCount': value['totalRowCount'],
        'columnCount': value['columnCount'],
        'columns': value['columns'],
        'schema': ((value['schema'] as Array<any>).map(SqlResultColumnSchemaToJSON)),
        'truncated': value['truncated'],
        'limit': value['limit'],
    };
}

