/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SqlQueryResultRow } from './SqlQueryResultRow';
import {
    SqlQueryResultRowFromJSON,
    SqlQueryResultRowFromJSONTyped,
    SqlQueryResultRowToJSON,
    SqlQueryResultRowToJSONTyped,
} from './SqlQueryResultRow';

/**
 * SqlQueryResultPage 的公开协议结构。 / Public contract for sql query result page.
 * @export
 * @interface SqlQueryResultPage
 */
export interface SqlQueryResultPage {
    /**
     * 字段 resultId / result id field。
     */
    resultId: string;
    /**
     * 字段 sql / sql field。
     */
    sql: string;
    /**
     * 字段 columns / columns field。
     */
    columns: Array<string>;
    /**
     * 字段 rowCount / row count field。
     */
    rowCount: number;
    /**
     * 字段 columnCount / column count field。
     */
    columnCount: number;
    /**
     * 字段 current / current field。
     */
    current: number;
    /**
     * 大小（字节）或分页容量 / byte size or page size。
     */
    size: number;
    /**
     * 字段 total / total field。
     */
    total: number;
    /**
     * 记录列表 / records。
     */
    records: Array<SqlQueryResultRow>;
}

/**
 * Check if a given object implements the SqlQueryResultPage interface.
 */
export function instanceOfSqlQueryResultPage(value: object): value is SqlQueryResultPage {
    if (!('resultId' in value) || value['resultId'] === undefined) return false;
    if (!('sql' in value) || value['sql'] === undefined) return false;
    if (!('columns' in value) || value['columns'] === undefined) return false;
    if (!('rowCount' in value) || value['rowCount'] === undefined) return false;
    if (!('columnCount' in value) || value['columnCount'] === undefined) return false;
    if (!('current' in value) || value['current'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function SqlQueryResultPageFromJSON(json: any): SqlQueryResultPage {
    return SqlQueryResultPageFromJSONTyped(json, false);
}

export function SqlQueryResultPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SqlQueryResultPage {
    if (json == null) {
        return json;
    }
    return {
        
        'resultId': json['resultId'],
        'sql': json['sql'],
        'columns': json['columns'],
        'rowCount': json['rowCount'],
        'columnCount': json['columnCount'],
        'current': json['current'],
        'size': json['size'],
        'total': json['total'],
        'records': ((json['records'] as Array<any>).map(SqlQueryResultRowFromJSON)),
    };
}

export function SqlQueryResultPageToJSON(json: any): SqlQueryResultPage {
    return SqlQueryResultPageToJSONTyped(json, false);
}

export function SqlQueryResultPageToJSONTyped(value?: SqlQueryResultPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resultId': value['resultId'],
        'sql': value['sql'],
        'columns': value['columns'],
        'rowCount': value['rowCount'],
        'columnCount': value['columnCount'],
        'current': value['current'],
        'size': value['size'],
        'total': value['total'],
        'records': ((value['records'] as Array<any>).map(SqlQueryResultRowToJSON)),
    };
}

