/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * SystemChatMessage 的公开协议结构。 / Public contract for system chat message.
 * @export
 * @interface SystemChatMessage
 */
export interface SystemChatMessage {
    /**
     * 类型判别值 / type discriminator。
     */
    type: SystemChatMessageTypeEnum;
    /**
     * 字段 text / text field。
     */
    text: string;
    /**
     * 字段 metadataRawJson / metadata raw json field。
     */
    metadataRawJson?: string | null;
}


/**
 * @export
 */
export const SystemChatMessageTypeEnum = {
    System: 'SYSTEM',
} as const;
export type SystemChatMessageTypeEnum = typeof SystemChatMessageTypeEnum[keyof typeof SystemChatMessageTypeEnum];


/**
 * Check if a given object implements the SystemChatMessage interface.
 */
export function instanceOfSystemChatMessage(value: object): value is SystemChatMessage {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'SYSTEM') return false;
    
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function SystemChatMessageFromJSON(json: any): SystemChatMessage {
    return SystemChatMessageFromJSONTyped(json, false);
}

export function SystemChatMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemChatMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'text': json['text'],
        'metadataRawJson': json['metadataRawJson'] === undefined ? undefined : json['metadataRawJson'] === null ? null : json['metadataRawJson'],
    };
}

export function SystemChatMessageToJSON(json: any): SystemChatMessage {
    return SystemChatMessageToJSONTyped(json, false);
}

export function SystemChatMessageToJSONTyped(value?: SystemChatMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'text': value['text'],
        'metadataRawJson': value['metadataRawJson'],
    };
}

