/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskProgressExtensionContent } from './TaskProgressExtensionContent';
import {
    TaskProgressExtensionContentFromJSON,
    TaskProgressExtensionContentFromJSONTyped,
    TaskProgressExtensionContentToJSON,
    TaskProgressExtensionContentToJSONTyped,
} from './TaskProgressExtensionContent';

/**
 * TaskProgressExtensionToolExtension 的公开协议结构。 / Public contract for task progress extension tool extension.
 * @export
 * @interface TaskProgressExtensionToolExtension
 */
export interface TaskProgressExtensionToolExtension {
    /**
     * 扩展类别判别值 / extension category discriminator。
     */
    category: TaskProgressExtensionToolExtensionCategoryEnum;
    /**
     * 与类别对应的强类型内容 / strongly typed content for the category。
     */
    content: TaskProgressExtensionContent;
    /**
     * 是否使用独立视图渲染 / whether to use a dedicated view。
     */
    specialRender: boolean;
}


/**
 * @export
 */
export const TaskProgressExtensionToolExtensionCategoryEnum = {
    TaskProgress: 'taskProgress',
} as const;
export type TaskProgressExtensionToolExtensionCategoryEnum = typeof TaskProgressExtensionToolExtensionCategoryEnum[keyof typeof TaskProgressExtensionToolExtensionCategoryEnum];


/**
 * Check if a given object implements the TaskProgressExtensionToolExtension interface.
 */
export function instanceOfTaskProgressExtensionToolExtension(value: object): value is TaskProgressExtensionToolExtension {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (value['category'] !== 'taskProgress') return false;
    
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('specialRender' in value) || value['specialRender'] === undefined) return false;
    return true;
}

export function TaskProgressExtensionToolExtensionFromJSON(json: any): TaskProgressExtensionToolExtension {
    return TaskProgressExtensionToolExtensionFromJSONTyped(json, false);
}

export function TaskProgressExtensionToolExtensionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskProgressExtensionToolExtension {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'],
        'content': TaskProgressExtensionContentFromJSON(json['content']),
        'specialRender': json['specialRender'],
    };
}

export function TaskProgressExtensionToolExtensionToJSON(json: any): TaskProgressExtensionToolExtension {
    return TaskProgressExtensionToolExtensionToJSONTyped(json, false);
}

export function TaskProgressExtensionToolExtensionToJSONTyped(value?: TaskProgressExtensionToolExtension | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'content': TaskProgressExtensionContentToJSON(value['content']),
        'specialRender': value['specialRender'],
    };
}

