/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ToolResponse 的公开协议结构。 / Public contract for tool response.
 * @export
 * @interface ToolResponse
 */
export interface ToolResponse {
    /**
     * 字段 id / id field。
     */
    id: string;
    /**
     * 字段 name / name field。
     */
    name: string;
    /**
     * 当前状态 / current status。
     */
    status: string;
    /**
     * 字段 responseData / response data field。
     */
    responseData: string;
    /**
     * 字段 metadataRawJson / metadata raw json field。
     */
    metadataRawJson: string;
}

/**
 * Check if a given object implements the ToolResponse interface.
 */
export function instanceOfToolResponse(value: object): value is ToolResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('responseData' in value) || value['responseData'] === undefined) return false;
    if (!('metadataRawJson' in value) || value['metadataRawJson'] === undefined) return false;
    return true;
}

export function ToolResponseFromJSON(json: any): ToolResponse {
    return ToolResponseFromJSONTyped(json, false);
}

export function ToolResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'status': json['status'],
        'responseData': json['responseData'],
        'metadataRawJson': json['metadataRawJson'],
    };
}

export function ToolResponseToJSON(json: any): ToolResponse {
    return ToolResponseToJSONTyped(json, false);
}

export function ToolResponseToJSONTyped(value?: ToolResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'status': value['status'],
        'responseData': value['responseData'],
        'metadataRawJson': value['metadataRawJson'],
    };
}

