/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * UnknownAiChatBriefEvent 的公开协议结构。 / Public contract for unknown ai chat brief event.
 * @export
 * @interface UnknownAiChatBriefEvent
 */
export interface UnknownAiChatBriefEvent {
    /**
     * 类型判别值 / type discriminator。
     */
    type: string;
    /**
     * 未识别对象的原始 JSON / raw JSON for an unrecognized object。
     */
    rawJson: string;
}

/**
 * Check if a given object implements the UnknownAiChatBriefEvent interface.
 */
export function instanceOfUnknownAiChatBriefEvent(value: object): value is UnknownAiChatBriefEvent {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('rawJson' in value) || value['rawJson'] === undefined) return false;
    return true;
}

export function UnknownAiChatBriefEventFromJSON(json: any): UnknownAiChatBriefEvent {
    return UnknownAiChatBriefEventFromJSONTyped(json, false);
}

export function UnknownAiChatBriefEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnknownAiChatBriefEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'rawJson': json['rawJson'],
    };
}

export function UnknownAiChatBriefEventToJSON(json: any): UnknownAiChatBriefEvent {
    return UnknownAiChatBriefEventToJSONTyped(json, false);
}

export function UnknownAiChatBriefEventToJSONTyped(value?: UnknownAiChatBriefEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'rawJson': value['rawJson'],
    };
}

