/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InputTokenBreakdown } from './InputTokenBreakdown';
import {
    InputTokenBreakdownFromJSON,
    InputTokenBreakdownFromJSONTyped,
    InputTokenBreakdownToJSON,
    InputTokenBreakdownToJSONTyped,
} from './InputTokenBreakdown';

/**
 * Usage 的公开协议结构。 / Public contract for usage.
 * @export
 * @interface Usage
 */
export interface Usage {
    /**
     * 输入 Token 数 / input token count。
     */
    inputTokens: number;
    /**
     * 输出 Token 数 / output token count。
     */
    outputTokens: number;
    /**
     * 总 Token 数 / total token count。
     */
    readonly totalTokens: number;
    /**
     * 字段 inputTokenBreakdown / input token breakdown field。
     */
    inputTokenBreakdown?: InputTokenBreakdown | null;
    /**
     * 字段 reasoningTokens / reasoning tokens field。
     */
    reasoningTokens?: number | null;
    /**
     * 字段 cacheHitRate / cache hit rate field。
     */
    readonly cacheHitRate?: number | null;
    /**
     * 字段 inputBreakdownCoverageRate / input breakdown coverage rate field。
     */
    readonly inputBreakdownCoverageRate?: number | null;
}

/**
 * Check if a given object implements the Usage interface.
 */
export function instanceOfUsage(value: object): value is Usage {
    if (!('inputTokens' in value) || value['inputTokens'] === undefined) return false;
    if (!('outputTokens' in value) || value['outputTokens'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    return true;
}

export function UsageFromJSON(json: any): Usage {
    return UsageFromJSONTyped(json, false);
}

export function UsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Usage {
    if (json == null) {
        return json;
    }
    return {
        
        'inputTokens': json['inputTokens'],
        'outputTokens': json['outputTokens'],
        'totalTokens': json['totalTokens'],
        'inputTokenBreakdown': json['inputTokenBreakdown'] === undefined ? undefined : json['inputTokenBreakdown'] === null ? null : InputTokenBreakdownFromJSON(json['inputTokenBreakdown']),
        'reasoningTokens': json['reasoningTokens'] === undefined ? undefined : json['reasoningTokens'] === null ? null : json['reasoningTokens'],
        'cacheHitRate': json['cacheHitRate'] === undefined ? undefined : json['cacheHitRate'] === null ? null : json['cacheHitRate'],
        'inputBreakdownCoverageRate': json['inputBreakdownCoverageRate'] === undefined ? undefined : json['inputBreakdownCoverageRate'] === null ? null : json['inputBreakdownCoverageRate'],
    };
}

export function UsageToJSON(json: any): Usage {
    return UsageToJSONTyped(json, false);
}

export function UsageToJSONTyped(value?: Omit<Usage, 'totalTokens'|'cacheHitRate'|'inputBreakdownCoverageRate'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inputTokens': value['inputTokens'],
        'outputTokens': value['outputTokens'],
        'inputTokenBreakdown': InputTokenBreakdownToJSON(value['inputTokenBreakdown']),
        'reasoningTokens': value['reasoningTokens'],
    };
}

