/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InputTokenBreakdown } from './InputTokenBreakdown';
import {
    InputTokenBreakdownFromJSON,
    InputTokenBreakdownFromJSONTyped,
    InputTokenBreakdownToJSON,
    InputTokenBreakdownToJSONTyped,
} from './InputTokenBreakdown';

/**
 * Usage 的公开协议结构。 / Public contract for usage.
 * @export
 * @interface Usage
 */
export interface Usage {
    /**
     * 输入 Token 数 / input token count。
     */
    inputTokens: number;
    /**
     * 输出 Token 数 / output token count。
     */
    outputTokens: number;
    /**
     * 总 Token 数 / total token count。
     */
    readonly totalTokens: number;
    /**
     * 字段 inputTokenBreakdown / input token breakdown field。
     */
    inputTokenBreakdown?: InputTokenBreakdown | null;
    /**
     * 字段 reasoningTokens / reasoning tokens field。
     */
    reasoningTokens?: number | null;
    /**
     * 字段 cacheHitRate / cache hit rate field。
     */
    readonly cacheHitRate?: number | null;
    /**
     * 字段 inputBreakdownCoverageRate / input breakdown coverage rate field。
     */
    readonly inputBreakdownCoverageRate?: number | null;
}

/**
 * Check if a given object implements the Usage interface.
 */
export function instanceOfUsage(value: object): value is Usage {
    if (!('inputTokens' in value) || value['inputTokens'] === undefined) return false;
    if (!('outputTokens' in value) || value['outputTokens'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    return true;
}

export function UsageFromJSON(json: any): Usage {
    return UsageFromJSONTyped(json, false);
}

export function UsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Usage {
    if (json == null) {
        return json;
    }
    return {
        
        'inputTokens': json['inputTokens'],
        'outputTokens': json['outputTokens'],
        'totalTokens': json['totalTokens'],
        'inputTokenBreakdown': json['inputTokenBreakdown'] === undefined ? undefined : json['inputTokenBreakdown'] === null ? null : InputTokenBreakdownFromJSON(json['inputTokenBreakdown']),
        'reasoningTokens': json['reasoningTokens'] === undefined ? undefined : json['reasoningTokens'] === null ? null : json['reasoningTokens'],
        'cacheHitRate': json['cacheHitRate'] === undefined ? undefined : json['cacheHitRate'] === null ? null : json['cacheHitRate'],
        'inputBreakdownCoverageRate': json['inputBreakdownCoverageRate'] === undefined ? undefined : json['inputBreakdownCoverageRate'] === null ? null : json['inputBreakdownCoverageRate'],
    };
}

export function UsageToJSON(json: any): Usage {
    return UsageToJSONTyped(json, false);
}

export function UsageToJSONTyped(value?: Omit<Usage, 'totalTokens'|'cacheHitRate'|'inputBreakdownCoverageRate'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inputTokens': value['inputTokens'],
        'outputTokens': value['outputTokens'],
        'inputTokenBreakdown': InputTokenBreakdownToJSON(value['inputTokenBreakdown']),
        'reasoningTokens': value['reasoningTokens'],
    };
}

