/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * 本契约描述灵涯 Agents 面向可信服务端的公开渠道 API，使用 OPENAPI-HMAC-SHA256-V1 验证请求，不包含 Studio 管理接口。在线文档只展示请求，不会在浏览器中收集或保存 secret。  This contract describes the public Lingya Agents channel API for trusted servers. Requests use OPENAPI-HMAC-SHA256-V1, and Studio administration endpoints are excluded. The online reference only displays requests and never collects or stores a secret in the browser.  ## 快速开始 / Quick start  1. 读取 Configuration，确认模型和附件限制。 / Read Configuration to discover model and attachment limits.  2. 在本地固定最终 method、raw path、raw query、Content-Type 和 body 字节，再生成签名。 / Finalize method, raw path, raw query, Content-Type, and body bytes locally before signing.  3. 按业务分组调用接口；SSE 断开后使用 Events 补取。 / Call the appropriate business group and use Events for recovery after an SSE disconnect.  ## 公共错误 / Common errors  `401` 签名、时间戳或 nonce 无效；`403` 资源不属于当前渠道用户；`413` 请求体过大；`422` 参数校验失败；`429` 请求过于频繁；`500` 服务内部错误；`503` 依赖或执行服务暂不可用。  `401` invalid signature, timestamp, or nonce; `403` resource not owned by the current channel user; `413` request body too large; `422` validation failed; `429` rate limited; `500` internal error; `503` dependency or execution service unavailable.
 *
 * The version of the OpenAPI document: 0.1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * UserInputAnswerInput 的公开协议结构。 / Public contract for user input answer input.
 * @export
 * @interface UserInputAnswerInput
 */
export interface UserInputAnswerInput {
    /**
     * 会话 ID / conversation ID。
     */
    conversationId: string;
    /**
     * 消息 ID / message ID。
     */
    messageId: string;
    /**
     * 字段 questionId / question id field。
     */
    questionId: string;
    /**
     * 字段 selectedOptions / selected options field。
     */
    selectedOptions: Array<string>;
    /**
     * 字段 customInput / custom input field。
     */
    customInput?: string | null;
}

/**
 * Check if a given object implements the UserInputAnswerInput interface.
 */
export function instanceOfUserInputAnswerInput(value: object): value is UserInputAnswerInput {
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    if (!('selectedOptions' in value) || value['selectedOptions'] === undefined) return false;
    return true;
}

export function UserInputAnswerInputFromJSON(json: any): UserInputAnswerInput {
    return UserInputAnswerInputFromJSONTyped(json, false);
}

export function UserInputAnswerInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInputAnswerInput {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationId': json['conversationId'],
        'messageId': json['messageId'],
        'questionId': json['questionId'],
        'selectedOptions': json['selectedOptions'],
        'customInput': json['customInput'] === undefined ? undefined : json['customInput'] === null ? null : json['customInput'],
    };
}

export function UserInputAnswerInputToJSON(json: any): UserInputAnswerInput {
    return UserInputAnswerInputToJSONTyped(json, false);
}

export function UserInputAnswerInputToJSONTyped(value?: UserInputAnswerInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversationId': value['conversationId'],
        'messageId': value['messageId'],
        'questionId': value['questionId'],
        'selectedOptions': value['selectedOptions'],
        'customInput': value['customInput'],
    };
}

