/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * UserInputStatus 的公开协议结构。 / Public contract for user input status.
 * @export
 * @interface UserInputStatus
 */
export interface UserInputStatus {
    /**
     * 字段 pending / pending field。
     */
    pending: boolean;
    /**
     * 字段 question / question field。
     */
    question?: string | null;
    /**
     * 字段 questionDetails / question details field。
     */
    questionDetails?: string | null;
    /**
     * 字段 options / options field。
     */
    options?: Array<string> | null;
    /**
     * 字段 multiple / multiple field。
     */
    multiple?: boolean | null;
}

/**
 * Check if a given object implements the UserInputStatus interface.
 */
export function instanceOfUserInputStatus(value: object): value is UserInputStatus {
    if (!('pending' in value) || value['pending'] === undefined) return false;
    return true;
}

export function UserInputStatusFromJSON(json: any): UserInputStatus {
    return UserInputStatusFromJSONTyped(json, false);
}

export function UserInputStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInputStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'pending': json['pending'],
        'question': json['question'] === undefined ? undefined : json['question'] === null ? null : json['question'],
        'questionDetails': json['questionDetails'] === undefined ? undefined : json['questionDetails'] === null ? null : json['questionDetails'],
        'options': json['options'] === undefined ? undefined : json['options'] === null ? null : json['options'],
        'multiple': json['multiple'] === undefined ? undefined : json['multiple'] === null ? null : json['multiple'],
    };
}

export function UserInputStatusToJSON(json: any): UserInputStatus {
    return UserInputStatusToJSONTyped(json, false);
}

export function UserInputStatusToJSONTyped(value?: UserInputStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pending': value['pending'],
        'question': value['question'],
        'questionDetails': value['questionDetails'],
        'options': value['options'],
        'multiple': value['multiple'],
    };
}

