/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * UserInputAnswerInput 的公开协议结构。 / Public contract for user input answer input.
 * @export
 * @interface UserInputAnswerInput
 */
export interface UserInputAnswerInput {
    /**
     * 会话 ID / conversation ID。
     */
    conversationId: string;
    /**
     * 消息 ID / message ID。
     */
    messageId: string;
    /**
     * 字段 questionId / question id field。
     */
    questionId: string;
    /**
     * 字段 selectedOptions / selected options field。
     */
    selectedOptions: Array<string>;
    /**
     * 字段 customInput / custom input field。
     */
    customInput?: string | null;
}

/**
 * Check if a given object implements the UserInputAnswerInput interface.
 */
export function instanceOfUserInputAnswerInput(value: object): value is UserInputAnswerInput {
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    if (!('selectedOptions' in value) || value['selectedOptions'] === undefined) return false;
    return true;
}

export function UserInputAnswerInputFromJSON(json: any): UserInputAnswerInput {
    return UserInputAnswerInputFromJSONTyped(json, false);
}

export function UserInputAnswerInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInputAnswerInput {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationId': json['conversationId'],
        'messageId': json['messageId'],
        'questionId': json['questionId'],
        'selectedOptions': json['selectedOptions'],
        'customInput': json['customInput'] === undefined ? undefined : json['customInput'] === null ? null : json['customInput'],
    };
}

export function UserInputAnswerInputToJSON(json: any): UserInputAnswerInput {
    return UserInputAnswerInputToJSONTyped(json, false);
}

export function UserInputAnswerInputToJSONTyped(value?: UserInputAnswerInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversationId': value['conversationId'],
        'messageId': value['messageId'],
        'questionId': value['questionId'],
        'selectedOptions': value['selectedOptions'],
        'customInput': value['customInput'],
    };
}

