/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * VariableBinding 的公开协议结构。 / Public contract for variable binding.
 * @export
 * @interface VariableBinding
 */
export interface VariableBinding {
    /**
     * 字段 name / name field。
     */
    name: string;
    /**
     * 字段 value / value field。
     */
    value: string;
}

/**
 * Check if a given object implements the VariableBinding interface.
 */
export function instanceOfVariableBinding(value: object): value is VariableBinding {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function VariableBindingFromJSON(json: any): VariableBinding {
    return VariableBindingFromJSONTyped(json, false);
}

export function VariableBindingFromJSONTyped(json: any, ignoreDiscriminator: boolean): VariableBinding {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
    };
}

export function VariableBindingToJSON(json: any): VariableBinding {
    return VariableBindingToJSONTyped(json, false);
}

export function VariableBindingToJSONTyped(value?: VariableBinding | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

