/* tslint:disable */
/* eslint-disable */
/**
 * Lingya Agents OpenAPI
 * Public, tenant-scoped Agent channel API authenticated with OPENAPI-HMAC-SHA256-V1. Studio administration endpoints are not part of this contract.
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageInfo } from './PageInfo';
import {
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
    PageInfoToJSONTyped,
} from './PageInfo';
import type { WorkspaceFile } from './WorkspaceFile';
import {
    WorkspaceFileFromJSON,
    WorkspaceFileFromJSONTyped,
    WorkspaceFileToJSON,
    WorkspaceFileToJSONTyped,
} from './WorkspaceFile';

/**
 * WorkspaceFilePage 的公开协议结构。 / Public contract for workspace file page.
 * @export
 * @interface WorkspaceFilePage
 */
export interface WorkspaceFilePage {
    /**
     * 记录列表 / records。
     */
    records: Array<WorkspaceFile>;
    /**
     * 分页信息 / page metadata。
     */
    page: PageInfo;
}

/**
 * Check if a given object implements the WorkspaceFilePage interface.
 */
export function instanceOfWorkspaceFilePage(value: object): value is WorkspaceFilePage {
    if (!('records' in value) || value['records'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    return true;
}

export function WorkspaceFilePageFromJSON(json: any): WorkspaceFilePage {
    return WorkspaceFilePageFromJSONTyped(json, false);
}

export function WorkspaceFilePageFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceFilePage {
    if (json == null) {
        return json;
    }
    return {
        
        'records': ((json['records'] as Array<any>).map(WorkspaceFileFromJSON)),
        'page': PageInfoFromJSON(json['page']),
    };
}

export function WorkspaceFilePageToJSON(json: any): WorkspaceFilePage {
    return WorkspaceFilePageToJSONTyped(json, false);
}

export function WorkspaceFilePageToJSONTyped(value?: WorkspaceFilePage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'records': ((value['records'] as Array<any>).map(WorkspaceFileToJSON)),
        'page': PageInfoToJSON(value['page']),
    };
}

